import { useCallback, useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { BarChart3, FileSpreadsheet, Printer, Search } from "lucide-react";
import { toast } from "sonner";
import AgroLayout from "@/components/agro/AgroLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { api } from "@/lib/api";
import { REALTIME_CHANGE_EVENT, realtimeChangeTouches } from "@/lib/realtime";
import type { AgroCrop, AgroFarm, AgroReport, AgroReportGroup, AgroSeason, AgroStockLocation } from "@/lib/agro";
import { agroOperationLabel, formatAgroCurrency, formatAgroDate, formatAgroNumber } from "@/lib/agro";

function firstDay() { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-01`; }
function today() { return new Date().toISOString().slice(0, 10); }
function escapeHtml(value: unknown) { return String(value ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c] || c)); }

export default function AgroRelatorios() {
  const [tab, setTab] = useState("resumo");
  const [data, setData] = useState<AgroReport | null>(null);
  const [locations, setLocations] = useState<AgroStockLocation[]>([]);
  const [farms, setFarms] = useState<AgroFarm[]>([]);
  const [seasons, setSeasons] = useState<AgroSeason[]>([]);
  const [crops, setCrops] = useState<AgroCrop[]>([]);
  const [filters, setFilters] = useState({ from: firstDay(), to: today(), localId: "", fazendaId: "", safraId: "", culturaId: "" });
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");

  const loadBase = useCallback(async () => {
    try { const [l, f, s, c] = await Promise.all([api.get<AgroStockLocation[]>("/agro/locais"), api.get<AgroFarm[]>("/agro/fazendas"), api.get<AgroSeason[]>("/agro/safras"), api.get<AgroCrop[]>("/agro/culturas")]); setLocations(l.data || []); setFarms(f.data || []); setSeasons(s.data || []); setCrops(c.data || []); } catch { /* relatório ainda pode abrir */ }
  }, []);
  const load = useCallback(async (silent = false) => {
    if (!silent) setLoading(true);
    try { const response = await api.get<AgroReport>("/agro/relatorios", { params: filters }); setData(response.data); }
    catch (error: any) { toast.error(error?.response?.data?.message || "Não foi possível gerar os relatórios Agro."); }
    finally { if (!silent) setLoading(false); }
  }, [filters]);
  useEffect(() => { void loadBase(); }, [loadBase]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { let timer: number | undefined; const handler = (event: Event) => { if (!realtimeChangeTouches(event, "agro", "agro/relatorios", "agro/estoque", "agro/movimentacoes", "agro/operacoes", "agro/inventarios", "agro/transferencias")) return; if (timer) clearTimeout(timer); timer = window.setTimeout(() => void load(true), 300); }; window.addEventListener(REALTIME_CHANGE_EVENT, handler); return () => { if (timer) clearTimeout(timer); window.removeEventListener(REALTIME_CHANGE_EVENT, handler); }; }, [load]);

  const filteredConsumptions = useMemo(() => { const q = search.trim().toLocaleLowerCase("pt-BR"); if (!q) return data?.consumos || []; return (data?.consumos || []).filter((r: any) => [r.produto?.nome, r.produto?.codigo, r.operacao?.lavoura?.talhao?.fazenda?.nome, r.operacao?.lavoura?.talhao?.nome, r.operacao?.lavoura?.cultura?.nome, r.operacao?.lavoura?.safra?.nome, r.local?.nome].some((v) => String(v || "").toLocaleLowerCase("pt-BR").includes(q))); }, [data?.consumos, search]);

  function exportXlsx() {
    if (!data) return;
    const wb = XLSX.utils.book_new();
    const resumo = [["Período", `${formatAgroDate(data.periodo.from)} a ${formatAgroDate(data.periodo.to)}`], ["Valor em estoque", data.resumo.valorEstoqueAtual], ["Entradas", data.resumo.entradasValor], ["Consumo", data.resumo.consumoValor], ["Ajustes", data.resumo.ajustesValor], ["Área analisada (ha)", data.resumo.areaHa], ["Custo por ha", data.resumo.custoPorHa]];
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(resumo), "Resumo");
    const stockRows = data.estoque.map((r) => ({ Codigo: r.produto.codigo, Produto: r.produto.nome, Unidade: r.produto.unidadeMedida, Saldo: r.estoque, "Custo medio": r.custoMedio, "Valor estoque": r.valorEstoque, "Estoque baixo": r.abaixoMinimo ? "Sim" : "Não", Validade: r.proximaValidade || "" }));
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(stockRows), "Estoque");
    const groupSheet = (rows: AgroReportGroup[]) => XLSX.utils.json_to_sheet(rows.map((r) => ({ Grupo: r.label, Quantidade: r.quantidade, Custo: r.custo, "Area ha": r.areaHa, "Custo por ha": r.custoPorHa })));
    XLSX.utils.book_append_sheet(wb, groupSheet(data.consumoPorProduto), "Por produto"); XLSX.utils.book_append_sheet(wb, groupSheet(data.consumoPorFazenda), "Por fazenda"); XLSX.utils.book_append_sheet(wb, groupSheet(data.consumoPorTalhao), "Por talhao"); XLSX.utils.book_append_sheet(wb, groupSheet(data.consumoPorSafra), "Por safra"); XLSX.utils.book_append_sheet(wb, groupSheet(data.consumoPorCultura), "Por cultura");
    XLSX.writeFile(wb, `radasa-agro-${data.periodo.from}-${data.periodo.to}.xlsx`, { compression: true }); toast.success("Relatório Agro XLSX exportado.");
  }
  function exportPdf() {
    if (!data) return;
    const popup = window.open("", "_blank", "width=1100,height=800"); if (!popup) return toast.error("Permita pop-ups para gerar o PDF.");
    const groups = data.consumoPorFazenda.slice(0, 20).map((r) => `<tr><td>${escapeHtml(r.label)}</td><td style="text-align:right">${formatAgroCurrency(r.custo)}</td><td style="text-align:right">${formatAgroNumber(r.areaHa)} ha</td><td style="text-align:right">${formatAgroCurrency(r.custoPorHa)}</td></tr>`).join("");
    const stock = data.estoque.slice(0, 100).map((r) => `<tr><td>${escapeHtml(r.produto.codigo)}</td><td>${escapeHtml(r.produto.nome)}</td><td style="text-align:right">${formatAgroNumber(r.estoque)} ${escapeHtml(r.produto.unidadeMedida)}</td><td style="text-align:right">${formatAgroCurrency(r.custoMedio)}</td><td style="text-align:right">${formatAgroCurrency(r.valorEstoque)}</td></tr>`).join("");
    popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Radasa Agro - Relatório</title><style>body{font-family:Arial,sans-serif;padding:28px;color:#111}h1{margin:0}p{color:#555}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:20px 0}.card{border:1px solid #ddd;border-radius:8px;padding:12px}.label{font-size:11px;color:#666}.value{font-size:18px;font-weight:700;margin-top:5px}table{border-collapse:collapse;width:100%;font-size:11px;margin:10px 0 24px}th,td{border:1px solid #ddd;padding:7px}th{background:#f3f4f6;text-align:left}@media print{button{display:none}}</style></head><body><h1>Radasa Agro — Relatório gerencial</h1><p>${formatAgroDate(data.periodo.from)} a ${formatAgroDate(data.periodo.to)}</p><div class="cards"><div class="card"><div class="label">Valor em estoque</div><div class="value">${formatAgroCurrency(data.resumo.valorEstoqueAtual)}</div></div><div class="card"><div class="label">Consumo</div><div class="value">${formatAgroCurrency(data.resumo.consumoValor)}</div></div><div class="card"><div class="label">Área</div><div class="value">${formatAgroNumber(data.resumo.areaHa)} ha</div></div><div class="card"><div class="label">Custo/ha</div><div class="value">${formatAgroCurrency(data.resumo.custoPorHa)}</div></div></div><h2>Consumo por fazenda</h2><table><thead><tr><th>Fazenda</th><th>Custo</th><th>Área</th><th>Custo/ha</th></tr></thead><tbody>${groups || '<tr><td colspan="4">Sem consumo no período.</td></tr>'}</tbody></table><h2>Estoque atual</h2><table><thead><tr><th>Código</th><th>Produto</th><th>Saldo</th><th>Custo médio</th><th>Valor</th></tr></thead><tbody>${stock}</tbody></table><button onclick="window.print()">Salvar como PDF / Imprimir</button><script>setTimeout(()=>window.print(),300)</script></body></html>`); popup.document.close();
  }

  const summary = data?.resumo;
  return <AgroLayout><div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">Agro / Relatórios</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">Dashboard e relatórios gerenciais</h1><p className="mt-2 text-sm text-muted-foreground">Custos por estoque, produto, fazenda, talhão, safra e cultura, calculados com custo médio ponderado.</p></div><div className="flex gap-2"><Button variant="outline" disabled={!data} onClick={exportXlsx}><FileSpreadsheet className="mr-2 h-4 w-4" />Excel</Button><Button variant="outline" disabled={!data} onClick={exportPdf}><Printer className="mr-2 h-4 w-4" />PDF</Button></div></div>
    <div className="grid gap-2 rounded-xl border bg-card p-3 sm:grid-cols-2 lg:grid-cols-6"><Input type="date" value={filters.from} onChange={(e) => setFilters((f) => ({ ...f, from: e.target.value }))} /><Input type="date" value={filters.to} onChange={(e) => setFilters((f) => ({ ...f, to: e.target.value }))} /><select className="h-9 rounded-md border bg-background px-2 text-sm" value={filters.localId} onChange={(e) => setFilters((f) => ({ ...f, localId: e.target.value }))}><option value="">Todos os locais</option>{locations.filter((l) => l.ativo).map((l) => <option key={l.id} value={l.id}>{l.nome}</option>)}</select><select className="h-9 rounded-md border bg-background px-2 text-sm" value={filters.fazendaId} onChange={(e) => setFilters((f) => ({ ...f, fazendaId: e.target.value }))}><option value="">Todas as fazendas</option>{farms.map((f) => <option key={f.id} value={f.id}>{f.nome}</option>)}</select><select className="h-9 rounded-md border bg-background px-2 text-sm" value={filters.safraId} onChange={(e) => setFilters((f) => ({ ...f, safraId: e.target.value }))}><option value="">Todas as safras</option>{seasons.map((s) => <option key={s.id} value={s.id}>{s.nome}</option>)}</select><select className="h-9 rounded-md border bg-background px-2 text-sm" value={filters.culturaId} onChange={(e) => setFilters((f) => ({ ...f, culturaId: e.target.value }))}><option value="">Todas as culturas</option>{crops.map((c) => <option key={c.id} value={c.id}>{c.nome}</option>)}</select></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-7">{[["Valor em estoque", formatAgroCurrency(summary?.valorEstoqueAtual || 0)], ["Entradas", formatAgroCurrency(summary?.entradasValor || 0)], ["Consumo", formatAgroCurrency(summary?.consumoValor || 0)], ["Ajustes", formatAgroCurrency(summary?.ajustesValor || 0)], ["Área analisada", `${formatAgroNumber(summary?.areaHa || 0)} ha`], ["Custo por ha", formatAgroCurrency(summary?.custoPorHa || 0)], ["Operações", summary?.operacoes || 0]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-4"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-xl font-bold">{loading && !data ? "—" : value}</div></CardContent></Card>)}</div>
    <Tabs value={tab} onValueChange={setTab}><TabsList className="flex h-auto flex-wrap"><TabsTrigger value="resumo"><BarChart3 />Resumo</TabsTrigger><TabsTrigger value="estoque">Estoque</TabsTrigger><TabsTrigger value="consumo">Consumo</TabsTrigger><TabsTrigger value="custos">Custos por área</TabsTrigger></TabsList>
      <TabsContent value="resumo"><div className="mt-4 grid gap-4 xl:grid-cols-2"><GroupCard title="Produtos mais consumidos" rows={data?.consumoPorProduto || []} /><GroupCard title="Consumo por fazenda" rows={data?.consumoPorFazenda || []} /><GroupCard title="Consumo por cultura" rows={data?.consumoPorCultura || []} /><div className="rounded-xl border bg-card p-4"><div className="font-semibold">Evolução mensal</div><div className="mt-4 space-y-3">{(data?.mensal || []).map((m) => { const max = Math.max(...(data?.mensal || []).map((x) => Math.max(x.entradas, x.consumo)), 1); return <div key={m.mes}><div className="mb-1 flex justify-between text-xs"><span>{m.mes}</span><span>Consumo {formatAgroCurrency(m.consumo)}</span></div><div className="h-2 overflow-hidden rounded bg-muted"><div className="h-full bg-primary" style={{ width: `${Math.min(100, (m.consumo / max) * 100)}%` }} /></div></div>; })}{!data?.mensal?.length && <div className="py-8 text-center text-sm text-muted-foreground">Sem movimentações no período.</div>}</div></div></div></TabsContent>
      <TabsContent value="estoque"><div className="mt-4 overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="bg-muted/40 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-4 py-3">Produto</th><th className="px-4 py-3 text-right">Saldo</th><th className="px-4 py-3 text-right">Custo médio</th><th className="px-4 py-3 text-right">Valor estoque</th><th className="px-4 py-3">Validade</th><th className="px-4 py-3">Situação</th></tr></thead><tbody className="divide-y">{(data?.estoque || []).map((r) => <tr key={r.produto.id}><td className="px-4 py-3"><div className="font-semibold">{r.produto.nome}</div><div className="text-xs text-muted-foreground">{r.produto.codigo}</div></td><td className="px-4 py-3 text-right">{formatAgroNumber(r.estoque)} {r.produto.unidadeMedida}</td><td className="px-4 py-3 text-right">{formatAgroCurrency(r.custoMedio)}</td><td className="px-4 py-3 text-right font-semibold">{formatAgroCurrency(r.valorEstoque)}</td><td className="px-4 py-3">{formatAgroDate(r.proximaValidade)}</td><td className="px-4 py-3">{r.abaixoMinimo ? <span className="text-amber-700">Estoque baixo</span> : "Normal"}</td></tr>)}</tbody></table></div></div></TabsContent>
      <TabsContent value="consumo"><div className="mt-4 space-y-3"><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar consumo..." /></div><div className="overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-muted/40 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-3 py-2">Data</th><th className="px-3 py-2">Produto</th><th className="px-3 py-2">Fazenda / Talhão</th><th className="px-3 py-2">Cultura / Safra</th><th className="px-3 py-2">Operação</th><th className="px-3 py-2">Local</th><th className="px-3 py-2 text-right">Quantidade</th><th className="px-3 py-2 text-right">Custo</th></tr></thead><tbody className="divide-y">{filteredConsumptions.map((r: any) => <tr key={r.id}><td className="px-3 py-2">{formatAgroDate(r.data)}</td><td className="px-3 py-2"><div className="font-medium">{r.produto?.nome}</div><div className="text-xs text-muted-foreground">{r.lote?.codigo || ""}</div></td><td className="px-3 py-2">{r.operacao?.lavoura?.talhao?.fazenda?.nome || "Saída manual"}<div className="text-xs text-muted-foreground">{r.operacao?.lavoura?.talhao?.nome || r.destino || ""}</div></td><td className="px-3 py-2">{r.operacao?.lavoura?.cultura?.nome || "—"}<div className="text-xs text-muted-foreground">{r.operacao?.lavoura?.safra?.nome || ""}</div></td><td className="px-3 py-2">{r.operacao ? agroOperationLabel(r.operacao.tipo) : "Saída"}</td><td className="px-3 py-2">{r.local?.nome || "—"}</td><td className="px-3 py-2 text-right">{formatAgroNumber(r.quantidade)} {r.produto?.unidadeMedida}</td><td className="px-3 py-2 text-right font-semibold">{formatAgroCurrency(r.custoTotal)}</td></tr>)}{filteredConsumptions.length === 0 && <tr><td colSpan={8} className="px-3 py-10 text-center text-muted-foreground">Sem consumo no período.</td></tr>}</tbody></table></div></div></div></TabsContent>
      <TabsContent value="custos"><div className="mt-4 grid gap-4 xl:grid-cols-2"><GroupCard title="Custo por talhão" rows={data?.consumoPorTalhao || []} showArea /><GroupCard title="Custo por safra" rows={data?.consumoPorSafra || []} showArea /><GroupCard title="Custo por cultura" rows={data?.consumoPorCultura || []} showArea /><GroupCard title="Custo por operação" rows={(data?.consumoPorOperacao || []).map((r) => ({ ...r, label: agroOperationLabel(r.id as any) }))} showArea /></div></TabsContent>
    </Tabs>
  </div></AgroLayout>;
}

function GroupCard({ title, rows, showArea = false }: { title: string; rows: AgroReportGroup[]; showArea?: boolean }) {
  return <div className="rounded-xl border bg-card p-4"><div className="font-semibold">{title}</div><div className="mt-3 divide-y">{rows.slice(0, 10).map((r) => <div key={r.id} className="flex items-center justify-between gap-3 py-2 text-sm"><div className="min-w-0"><div className="truncate font-medium">{r.label}</div>{showArea && <div className="text-xs text-muted-foreground">{formatAgroNumber(r.areaHa)} ha · {formatAgroCurrency(r.custoPorHa)}/ha</div>}</div><div className="shrink-0 text-right font-semibold">{formatAgroCurrency(r.custo)}</div></div>)}{rows.length === 0 && <div className="py-8 text-center text-sm text-muted-foreground">Sem dados no período.</div>}</div></div>;
}
