import { useEffect, useMemo, useState } from "react";
import Layout from "@/components/Layout";
import { useClientes, useProdutos, useRomaneios, useVeiculos } from "@/lib/store";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Command, CommandEmpty, CommandInput, CommandItem, CommandList } from "@/components/ui/command";
import { Check, ChevronDown, FileSpreadsheet, Printer, Tags } from "lucide-react";
import { BarChart, Bar, CartesianGrid, ComposedChart, Line, LineChart, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, Legend } from "recharts";
import * as XLSX from "xlsx";

type PageKey = "produtos"|"clientes"|"veiculos"|"consulta";
type PriceRule={id:string;produtoId:string;clienteId:string|null;vigenciaInicio:string;custoUnitarioLebrinha?:number;vendaUnitarioCliente:number};
type BiNfeItem={id:string;numero:string;serie:string;dataEmissao:string;codigo:string;descricao:string;quantidade:number;valorUnitario:number;valorTotal:number;};
type Fact={id:string;data:string;mes:string;romaneio:string;nf:string;serie:string;nfSerie:string;clienteId:string;cliente:string;razaoSocial:string;produtoId:string;produtoCod:string;produto:string;placa:string;quantidade:number;freteUnit:number;frete:number;faturamento:number;percentual:number;municipio:string;tipo:string;instrucao:string};
const BG:Record<PageKey,string>={
 produtos:"/bi-radasa/01_Desempenho_de_Produtos13111655955949386.png",
 clientes:"/bi-radasa/02_An_lise_por_Cliente44711027297808925.png",
 veiculos:"/bi-radasa/03_An_lise_por_Ve_culo8691259680367573.png",
 consulta:"/bi-radasa/04_Consulta_de_Documentos9125932487968521.png",
};
const BLUE="#0A508E",DARK="#072F52",YELLOW="#FFBD2B";
const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const pct=(v:number)=>`${v.toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})}%`;
const number=(v:number)=>v.toLocaleString("pt-BR",{maximumFractionDigits:2});
const month=(d:string)=>String(d||"").slice(0,7);
const monthLabel=(k:string)=>k?`${k.slice(5,7)}/${k.slice(0,4)}`:"—";
const norm=(v:unknown)=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR");
function aggregate<T>(rows:T[],key:(x:T)=>string,value:(x:T)=>number){const m=new Map<string,number>();for(const x of rows){const k=key(x)||"—";m.set(k,(m.get(k)||0)+value(x))}return [...m].map(([name,value])=>({name,value}))}
function aggregate2<T>(rows:T[],key:(x:T)=>string,a:(x:T)=>number,b:(x:T)=>number){const m=new Map<string,{a:number;b:number}>();for(const x of rows){const k=key(x)||"—";const cur=m.get(k)||{a:0,b:0};cur.a+=a(x);cur.b+=b(x);m.set(k,cur)}return [...m].map(([name,v])=>({name,a:v.a,b:v.b}))}
function Pos({x,y,w,h,children,className=""}:{x:number;y:number;w:number;h:number;children:any;className?:string}){return <div className={`absolute overflow-hidden ${className}`} style={{left:`${x/12.8}%`,top:`${y/7.2}%`,width:`${w/12.8}%`,height:`${h/7.2}%`}}>{children}</div>}
function Title({x,y,w,h,children,size=12}:{x:number;y:number;w:number;h:number;children:any;size?:number}){return <Pos x={x} y={y} w={w} h={h} className="flex items-center justify-center"><span style={{fontSize:size,fontWeight:700,color:"white",fontFamily:"Segoe UI,Arial,sans-serif"}}>{children}</span></Pos>}
function CardValue({x,y,w,h,value}:{x:number;y:number;w:number;h:number;value:string}){return <Pos x={x} y={y} w={w} h={h} className="flex items-center justify-center"><span style={{fontSize:17,fontWeight:600,color:"#202020",fontFamily:"Segoe UI,Arial,sans-serif"}}>{value}</span></Pos>}
function SearchableSlicer({x,y,w,h,value,onChange,options,placeholder}:{x:number;y:number;w:number;h:number;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[];placeholder:string}){
 const[open,setOpen]=useState(false);
 const selected=options.find(o=>o.value===value);
 const allLabel=placeholder==="NF/Série"?"Todas as NF/Séries":placeholder==="Placa"?"Todas as placas":placeholder==="Romaneio"?"Todos os romaneios":placeholder==="Cliente"?"Todos os clientes":"Todos os produtos";
 const allOptions=[{value:"TODOS",label:allLabel},...options];
 return <Pos x={x} y={y} w={w} h={h} className="flex items-center overflow-visible">
  <Popover open={open} onOpenChange={setOpen}>
   <PopoverTrigger asChild>
    <Button
     type="button"
     variant="outline"
     role="combobox"
     aria-expanded={open}
     title={value==="TODOS"?placeholder:(selected?.label||placeholder)}
     className="h-[68%] min-h-0 w-full justify-between rounded-[5px] border-slate-300 bg-white px-1.5 py-0 text-[9px] font-normal leading-none text-slate-800 shadow-[0_1px_2px_rgba(0,0,0,0.08)] hover:bg-white"
     style={{fontFamily:"Segoe UI,Arial,sans-serif"}}
    >
     <span className="min-w-0 flex-1 truncate text-left">{value==="TODOS"?placeholder:(selected?.label||placeholder)}</span>
     <ChevronDown className="ml-1 h-3 w-3 shrink-0 opacity-55"/>
    </Button>
   </PopoverTrigger>
   <PopoverContent align="start" sideOffset={3} className="w-[max(var(--radix-popover-trigger-width),240px)] rounded-md border-slate-200 p-0 shadow-lg">
    <Command>
     <CommandInput placeholder={`Pesquisar ${placeholder.toLowerCase()}...`} autoFocus className="h-8 text-[11px]"/>
     <CommandList className="max-h-[220px]">
      <CommandEmpty className="py-4 text-center text-[11px]">Nenhum resultado encontrado.</CommandEmpty>
      {allOptions.map(o=><CommandItem key={o.value} value={o.label} onSelect={()=>{onChange(o.value);setOpen(false)}} className="min-h-8 py-1.5 text-[11px]">
       <Check className={`mr-2 h-3.5 w-3.5 ${value===o.value?"opacity-100":"opacity-0"}`}/>
       <span className="truncate">{o.label}</span>
      </CommandItem>)}
     </CommandList>
    </Command>
   </PopoverContent>
  </Popover>
 </Pos>
}
function DateSlicer({x,y,w,h,from,to,setFrom,setTo}:{x:number;y:number;w:number;h:number;from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void}){
 return <Pos x={x} y={y} w={w} h={h} className="flex items-center gap-[3px]">
  <input aria-label="Data inicial" title="Data inicial" type="date" value={from} onChange={e=>setFrom(e.target.value)} className="h-[68%] min-w-0 flex-1 rounded-[5px] border border-slate-300 bg-white px-1 py-0 text-[8px] leading-none text-slate-800 shadow-[0_1px_2px_rgba(0,0,0,0.08)]"/>
  <input aria-label="Data final" title="Data final" type="date" value={to} onChange={e=>setTo(e.target.value)} className="h-[68%] min-w-0 flex-1 rounded-[5px] border border-slate-300 bg-white px-1 py-0 text-[8px] leading-none text-slate-800 shadow-[0_1px_2px_rgba(0,0,0,0.08)]"/>
 </Pos>
}
const tooltipStyle={fontSize:10,borderRadius:6};
const moneyTooltip=(value:unknown,name:unknown)=>{const n=Number(value||0);const label=String(name||"");if(label.includes("%"))return [pct(n),label];return [money(n),label] as [string,string]};
export default function BIGerencial(){
 const {items:romaneios}=useRomaneios();const{items:clientes}=useClientes();const{items:produtos}=useProdutos();const{items:veiculos}=useVeiculos();
 const[prices,setPrices]=useState<PriceRule[]>([]);
 const[priceOpen,setPriceOpen]=useState(false);
 const[priceDraft,setPriceDraft]=useState<Record<string,string>>({});
 const[savingPrices,setSavingPrices]=useState(false);
 const refreshPrices=()=>api.get<PriceRule[]>("/fiscal/precos-produtos").then(r=>setPrices(r.data||[])).catch(()=>setPrices([]));
 useEffect(()=>{void refreshPrices()},[]);
 const[page,setPage]=useState<PageKey>("produtos"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[clienteId,setClienteId]=useState("TODOS"),[placa,setPlaca]=useState("TODOS"),[produtoId,setProdutoId]=useState("TODOS"),[nf,setNf]=useState("TODOS"),[romaneio,setRomaneio]=useState("TODOS");
 const clienteMap=useMemo(()=>new Map(clientes.map(x=>[x.id,x])),[clientes]);
 const produtoMap=useMemo(()=>new Map(produtos.map(x=>[x.id,x])),[produtos]);
 const pickPrice=(produtoId:string,cliente:string,date:string)=>{
  const candidates=prices.filter(pr=>pr.produtoId===produtoId&&(pr.clienteId===cliente||pr.clienteId===null));
  if(!candidates.length)return 0;
  const effective=candidates.filter(pr=>pr.vigenciaInicio<=date).sort((a,b)=>Number(Boolean(b.clienteId))-Number(Boolean(a.clienteId))||b.vigenciaInicio.localeCompare(a.vigenciaInicio));
  if(effective.length)return Number(effective[0].vendaUnitarioCliente||0);
  // Se não houver uma vigência anterior ao romaneio, usa o cadastro mais recente
  // do cliente/produto (ou o padrão do produto) em vez de zerar silenciosamente.
  const latest=[...candidates].sort((a,b)=>Number(Boolean(b.clienteId))-Number(Boolean(a.clienteId))||b.vigenciaInicio.localeCompare(a.vigenciaInicio));
  return Number(latest[0]?.vendaUnitarioCliente||0);
 };
 const facts=useMemo<Fact[]>(()=>romaneios.flatMap(r=>r.produtos.map((p,i)=>{
  const c=clienteMap.get(p.clienteId||r.clienteId),prod=produtoMap.get(p.produtoId),date=r.dataManifesto,qtd=Number(p.quantidade||0),frete=Number(p.valorTotal||0);
  const clienteDoItem=p.clienteId||r.clienteId;
  const precoVenda=pickPrice(p.produtoId,clienteDoItem,date);
  const faturamento=qtd*precoVenda;
  return{id:`${r.id}-${p.id||i}`,data:date,mes:month(date),romaneio:p.romaneio||r.romaneios||"",nf:p.notaFiscal||"",serie:p.serieNf||"",nfSerie:p.notaFiscal?`${p.notaFiscal}${p.serieNf?`/${p.serieNf}`:""}`:"",clienteId:clienteDoItem,cliente:c?.nomeFantasia||c?.razaoSocial||"Sem cliente",razaoSocial:c?.razaoSocial||c?.nomeFantasia||"",produtoId:p.produtoId,produtoCod:prod?.codigoInterno||"",produto:prod?.nome||"Produto não identificado",placa:r.placaVeiculo||"Sem placa",quantidade:qtd,freteUnit:qtd?frete/qtd:0,frete,faturamento,percentual:faturamento?frete/faturamento*100:0,municipio:c?.enderecoFiscal||"",tipo:p.tipoManifesto||r.tipoManifesto,instrucao:p.instrucaoCobranca||""}
 })),[romaneios,clienteMap,produtoMap,prices]);
 const filtered=useMemo(()=>facts.filter(x=>(!from||x.data>=from)&&(!to||x.data<=to)&&(clienteId==="TODOS"||x.clienteId===clienteId)&&(placa==="TODOS"||x.placa===placa)&&(produtoId==="TODOS"||x.produtoId===produtoId)&&(nf==="TODOS"||x.nfSerie===nf)&&(romaneio==="TODOS"||x.romaneio===romaneio)),[facts,from,to,clienteId,placa,produtoId,nf,romaneio]);
 const totals=useMemo(()=>{const frete=filtered.reduce((s,x)=>s+x.frete,0),faturamento=filtered.reduce((s,x)=>s+x.faturamento,0),qtd=filtered.reduce((s,x)=>s+x.quantidade,0);return{frete,faturamento,qtd,perc:faturamento?frete/faturamento*100:0,ticket:filtered.length?frete/filtered.length:0,unit:qtd?frete/qtd:0,count:new Set(filtered.map(x=>x.romaneio).filter(Boolean)).size}},[filtered]);
 const byProduct=useMemo(()=>aggregate2(filtered,x=>`${x.produtoCod}${x.produtoCod?" - ":""}${x.produto}`,x=>x.faturamento,x=>x.frete).map(x=>({...x,percent:x.a?x.b/x.a*100:0})).sort((a,b)=>b.b-a.b),[filtered]);
 const byClient=useMemo(()=>aggregate2(filtered,x=>x.cliente,x=>x.faturamento,x=>x.frete).map(x=>({...x,percent:x.a?x.b/x.a*100:0})).sort((a,b)=>b.b-a.b),[filtered]);
 const byVehicle=useMemo(()=>aggregate2(filtered,x=>x.placa,x=>x.faturamento,x=>x.frete).map(x=>({...x,percent:x.a?x.b/x.a*100:0})).sort((a,b)=>b.a-a.a),[filtered]);
 const byMonth=useMemo(()=>aggregate2(filtered,x=>monthLabel(x.mes),x=>x.faturamento,x=>x.frete),[filtered]);
 // Produtos do BI: somente os que aparecem nos Romaneios.
 const productOpts=Array.from(new Map(
   facts
    .filter(x=>x.produtoId)
    .map(x=>[x.produtoId,{value:x.produtoId,label:`${x.produtoCod}${x.produtoCod?" - ":""}${x.produto}`}])
 ).values()).sort((a,b)=>a.label.localeCompare(b.label,"pt-BR",{numeric:true})),clientOpts=clientes.map(c=>({value:c.id,label:c.nomeFantasia||c.razaoSocial})),plateOpts=Array.from(new Set(veiculos.map(v=>v.placa).filter(Boolean))).map(v=>({value:v,label:v})),nfOpts=Array.from(new Set(facts.map(x=>x.nfSerie).filter(Boolean))).sort().map(v=>({value:v,label:v})),romOpts=Array.from(new Set(facts.map(x=>x.romaneio).filter(Boolean))).sort().map(v=>({value:v,label:v}));
 const romaneioProductIds=useMemo(()=>Array.from(new Set(romaneios.flatMap(r=>r.produtos.map(p=>p.produtoId).filter(Boolean)))),[romaneios]);
 const defaultPriceByProduct=useMemo(()=>{const map=new Map<string,PriceRule>();for(const pr of [...prices].filter(x=>x.clienteId===null).sort((a,b)=>b.vigenciaInicio.localeCompare(a.vigenciaInicio))){if(!map.has(pr.produtoId))map.set(pr.produtoId,pr)}return map},[prices]);
 const missingPriceCount=useMemo(()=>romaneioProductIds.filter(id=>!prices.some(p=>p.produtoId===id&&Number(p.vendaUnitarioCliente||0)>0)).length,[romaneioProductIds,prices]);
 const openPrices=()=>{const draft:Record<string,string>={};for(const id of romaneioProductIds){const current=defaultPriceByProduct.get(id);draft[id]=current?String(current.vendaUnitarioCliente):""}setPriceDraft(draft);setPriceOpen(true)};
 const savePrices=async()=>{setSavingPrices(true);try{const today=new Date().toISOString().slice(0,10);for(const id of romaneioProductIds){const value=Number(String(priceDraft[id]||"").replace(",","."));if(!Number.isFinite(value)||value<=0)continue;const existing=defaultPriceByProduct.get(id);if(existing){if(Math.abs(Number(existing.vendaUnitarioCliente)-value)>0.0001)await api.put(`/fiscal/precos-produtos/${(existing as any).id}`,{vendaUnitarioCliente:value})}else{await api.post("/fiscal/precos-produtos",{produtoId:id,clienteId:null,vigenciaInicio:"2020-01-01",custoUnitarioLebrinha:0,vendaUnitarioCliente:value})}}await refreshPrices();setPriceOpen(false)}finally{setSavingPrices(false)}};
 const reset=()=>{setFrom("");setTo("");setClienteId("TODOS");setPlaca("TODOS");setProdutoId("TODOS");setNf("TODOS");setRomaneio("TODOS")};
 const exportExcel=()=>{const ws=XLSX.utils.json_to_sheet(filtered.map(x=>({Data:x.data,Romaneio:x.romaneio,"NF/Série":x.nfSerie,Cliente:x.cliente,"Razão Social":x.razaoSocial,"Cód. Produto":x.produtoCod,Produto:x.produto,Quantidade:x.quantidade,Faturamento:x.faturamento,"Frete Total":x.frete,"% Frete/Faturamento":x.percentual,Placa:x.placa,Município:x.municipio})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Dados BI");XLSX.writeFile(wb,"Radasa-BI.xlsx")};
 const printPdf=()=>window.print();
 return <Layout><style>{`@media print{body *{visibility:hidden!important}#bi-print-root,#bi-print-root *{visibility:visible!important}#bi-print-root{position:fixed!important;left:0!important;top:0!important;width:100vw!important;height:auto!important;background:white!important}.bi-toolbar,.bi-tabs{display:none!important}.bi-canvas-wrap{margin:0!important;width:100%!important}.bi-canvas{width:100%!important;max-width:none!important;box-shadow:none!important;page-break-after:always!important;-webkit-print-color-adjust:exact!important;print-color-adjust:exact!important}@page{size:16in 9in;margin:0}}`}</style><div id="bi-print-root" className="space-y-4">
  <div className="bi-toolbar flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">BI Gerencial</h1><p className="text-sm text-muted-foreground">Visual original do Power BI, alimentado pelos dados do Radasa System.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={openPrices}><Tags className="mr-2 h-4 w-4"/>Preços do BI{missingPriceCount>0?` (${missingPriceCount} sem preço)`:""}</Button><Button variant="outline" onClick={exportExcel}><FileSpreadsheet className="mr-2 h-4 w-4"/>Excel</Button><Button onClick={printPdf}><Printer className="mr-2 h-4 w-4"/>Exportar PDF</Button></div></div>
  <div className="bi-tabs flex flex-wrap gap-2">{([['produtos','Desempenho de Produtos'],['clientes','Análise por Cliente'],['veiculos','Análise por Veículo'],['consulta','Consulta de Documentos']] as [PageKey,string][]).map(([k,l])=><Button key={k} size="sm" variant={page===k?"default":"outline"} onClick={()=>setPage(k)}>{l}</Button>)}</div>
  <Dialog open={priceOpen} onOpenChange={setPriceOpen}><DialogContent className="max-h-[85vh] max-w-3xl overflow-hidden"><DialogHeader><DialogTitle>Preços de venda usados no BI</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">Informe o valor unitário de venda de cada produto. O BI multiplica esse preço pela quantidade dos Romaneios para calcular Faturamento. Preços específicos por cliente cadastrados no Fiscal continuam tendo prioridade.</p><div className="max-h-[55vh] space-y-2 overflow-y-auto pr-2">{romaneioProductIds.map(id=>{const prod=produtoMap.get(id);return <div key={id} className="grid grid-cols-[1fr_150px] items-center gap-3 rounded-lg border p-3"><div className="min-w-0"><div className="truncate text-sm font-medium">{prod?.codigoInterno?`${prod.codigoInterno} - `:""}{prod?.nome||"Produto"}</div><div className="text-xs text-muted-foreground">{defaultPriceByProduct.has(id)?"Preço padrão cadastrado":"Preço padrão não cadastrado"}</div></div><div><Label className="text-xs">Preço unitário (R$)</Label><Input type="number" min="0" step="0.0001" value={priceDraft[id]||""} onChange={e=>setPriceDraft(cur=>({...cur,[id]:e.target.value}))} placeholder="0,00"/></div></div>})}</div><div className="flex justify-end gap-2 pt-2"><Button variant="outline" onClick={()=>setPriceOpen(false)}>Cancelar</Button><Button disabled={savingPrices} onClick={()=>void savePrices()}>{savingPrices?"Salvando...":"Salvar preços"}</Button></div></DialogContent></Dialog>
  <div className="bi-canvas-wrap overflow-x-auto rounded-lg border bg-slate-100 p-2"><div className="bi-canvas relative mx-auto aspect-[16/9] w-full max-w-[1280px] overflow-hidden bg-white" style={{fontFamily:"Segoe UI,Arial,sans-serif"}}><img src={BG[page]} className="absolute inset-0 h-full w-full select-none" draggable={false}/>
   {page==='produtos'&&<><Title x={75.6} y={14.9} w={343.9} h={49.6} size={20}>Desempenho Produtos</Title><Title x={278.6} y={79.5} w={259.5} h={31.2}>Frete x Faturamento por Produto</Title><Title x={480.3} y={417.5} w={319.6} h={31.4}>% Frete sobre o Faturamento do Produto</Title><Title x={931} y={151.7} w={217.3} h={31.4}>Detalhamento por Produto</Title><CommonSlicers from={from} to={to} setFrom={setFrom} setTo={setTo} placa={placa} setPlaca={setPlaca} clienteId={clienteId} setClienteId={setClienteId} produtoId={produtoId} setProdutoId={setProdutoId} plateOpts={plateOpts} clientOpts={clientOpts} productOpts={productOpts}/><Pos x={17.1} y={111.3} w={782.8} h={291.8}><ResponsiveContainer><BarChart data={byProduct.slice(0,10)} margin={{top:15,right:10,bottom:35,left:5}}><CartesianGrid vertical={false} stroke="#e6e6e6"/><XAxis dataKey="name" tick={{fontSize:9}} interval={0} angle={-15} textAnchor="end"/><YAxis hide/><Tooltip contentStyle={tooltipStyle} formatter={moneyTooltip}/><Legend verticalAlign="bottom"/><Bar dataKey="a" name="Faturamento" fill={BLUE} radius={[2,2,0,0]}/><Bar dataKey="b" name="Frete Total" fill={YELLOW} radius={[2,2,0,0]}/></BarChart></ResponsiveContainer></Pos><SimpleTable x={816.1} y={183.1} w={447.1} h={220} headers={['Produto','Faturamento','Frete Total','%']} rows={byProduct.slice(0,8).map(r=>[r.name,money(r.a),money(r.b),pct(r.percent)])}/><Pos x={17.1} y={448.9} w={1246.1} h={248.7}><ResponsiveContainer><BarChart layout="vertical" data={byProduct.slice(0,10)} margin={{top:10,right:55,bottom:10,left:140}}><XAxis type="number" hide/><YAxis type="category" dataKey="name" tick={{fontSize:9}} width={135}/><Tooltip contentStyle={tooltipStyle} formatter={(value)=>pct(Number(value||0))}/><Bar dataKey="percent" name="% Frete/Faturamento" fill={DARK} radius={[0,3,3,0]}/></BarChart></ResponsiveContainer></Pos></>}
   {page==='clientes'&&<><Title x={75.6} y={14.9} w={343.9} h={49.6} size={20}>Análise por Cliente</Title><Title x={56.6} y={80.8} w={115.8} h={31.4}>Faturamento</Title><Title x={269.3} y={82.6} w={115.8} h={31.4}>Frete Total</Title><Title x={26.9} y={199.3} w={175.1} h={31.4}>%Frete / Faturamento</Title><Title x={238.8} y={199.3} w={150.8} h={31.4}>Ticket Médio Frete</Title><Title x={34.1} y={316} w={150.8} h={31.4}>Frete por Unidade</Title><Title x={238.8} y={316} w={160.7} h={31.4}>Qtd. Fretes Produto</Title><Title x={473.1} y={82.6} w={267.5} h={31.4}>Faturamento x % Frete por Cliente</Title><Title x={904.9} y={149.9} w={259.5} h={31.4}>Evolução de Faturamento e Frete</Title><Title x={551.2} y={430.9} w={181.3} h={31.4}>Frete Total por Cliente</Title><CommonSlicers from={from} to={to} setFrom={setFrom} setTo={setTo} placa={placa} setPlaca={setPlaca} clienteId={clienteId} setClienteId={setClienteId} produtoId={produtoId} setProdutoId={setProdutoId} plateOpts={plateOpts} clientOpts={clientOpts} productOpts={productOpts}/><CardValue x={14.4} y={112.2} w={193.9} h={78.1} value={money(totals.faturamento)}/><CardValue x={220} y={112.2} w={187.6} h={78.1} value={money(totals.frete)}/><CardValue x={14.4} y={232.5} w={193.9} h={74.5} value={pct(totals.perc)}/><CardValue x={214.6} y={230.7} w={193} h={76.3} value={money(totals.ticket)}/><CardValue x={14.4} y={347.4} w={193.9} h={74.5} value={money(totals.unit)}/><CardValue x={220} y={347.4} w={187.6} h={74.5} value={number(totals.count)}/><Pos x={417.5} y={114} w={378.9} h={300.7}><ResponsiveContainer><ScatterChart margin={{top:10,right:15,bottom:18,left:0}}><CartesianGrid/><XAxis type="number" dataKey="a" name="Faturamento" tick={{fontSize:9}}/><YAxis type="number" dataKey="percent" name="% Frete" tick={{fontSize:9}}/><Tooltip cursor={{strokeDasharray:'3 3'}} contentStyle={tooltipStyle} formatter={moneyTooltip}/><Scatter data={byClient} fill={BLUE}/></ScatterChart></ResponsiveContainer></Pos><Pos x={807.1} y={181.3} w={456.1} h={233.4}><ResponsiveContainer><LineChart data={byMonth} margin={{top:15,right:10,bottom:20,left:0}}><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis hide/><Tooltip contentStyle={tooltipStyle} formatter={moneyTooltip}/><Legend verticalAlign="bottom"/><Line type="monotone" dataKey="a" name="Faturamento" stroke={BLUE} strokeWidth={2}/><Line type="monotone" dataKey="b" name="Frete Total" stroke={YELLOW} strokeWidth={2}/></LineChart></ResponsiveContainer></Pos><Pos x={14.4} y={462.3} w={1248.8} h={246.9}><ResponsiveContainer><BarChart layout="vertical" data={byClient.slice(0,12)} margin={{top:5,right:55,bottom:5,left:150}}><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={145} tick={{fontSize:9}}/><Tooltip contentStyle={tooltipStyle} formatter={moneyTooltip}/><Bar dataKey="b" name="Frete Total" fill={YELLOW} radius={[0,3,3,0]}/></BarChart></ResponsiveContainer></Pos></>}
   {page==='veiculos'&&<VehiclePage from={from} to={to} setFrom={setFrom} setTo={setTo} placa={placa} setPlaca={setPlaca} clienteId={clienteId} setClienteId={setClienteId} produtoId={produtoId} setProdutoId={setProdutoId} plateOpts={plateOpts} clientOpts={clientOpts} productOpts={productOpts} byVehicle={byVehicle} byMonth={byMonth} filtered={filtered}/>} 
   {page==='consulta'&&<><Title x={75.6} y={14.9} w={343.9} h={49.6} size={20}>Consulta Geral</Title><Title x={553} y={149.9} w={173.3} h={31.4}>Dados da Busca Geral</Title><DateSlicer x={825} y={14.4} w={220.8} h={48.5} from={from} to={to} setFrom={setFrom} setTo={setTo}/><SearchableSlicer x={1140.1} y={14.4} w={125.7} h={48.5} value={placa} onChange={setPlaca} options={plateOpts} placeholder="Placa"/><SearchableSlicer x={264.8} y={87.1} w={415.7} h={48.5} value={clienteId} onChange={setClienteId} options={clientOpts} placeholder="Cliente"/><SearchableSlicer x={765.8} y={87.1} w={117.6} h={48.5} value={romaneio} onChange={setRomaneio} options={romOpts} placeholder="Romaneio"/><SearchableSlicer x={946.2} y={87.1} w={147.2} h={48.5} value={nf} onChange={setNf} options={nfOpts} placeholder="NF/Série"/><SearchableSlicer x={1154.5} y={87.1} w={101.4} h={48.5} value={produtoId} onChange={setProdutoId} options={productOpts} placeholder="Produto"/><Pos x={8} y={184} w={1248} h={504} className="overflow-auto"><table className="w-full border-collapse bg-white text-[9px]"><thead className="sticky top-0 bg-[#0A508E] text-white"><tr>{['NF/Série','Romaneio','Razão Social','Cliente','Cód. Produto','Produto','Qtde','Faturamento','Frete Total','% Frete/Faturamento','Placa','Data','V. Unit. Frete','Município/Endereço'].map(h=><th key={h} className="border border-[#0A508E] px-1 py-2 text-left">{h}</th>)}</tr></thead><tbody>{filtered.slice(0,250).map(x=><tr key={x.id} className="odd:bg-[#F5F7FA]"><td className="border px-1 py-1">{x.nfSerie}</td><td className="border px-1 py-1">{x.romaneio}</td><td className="border px-1 py-1">{x.razaoSocial}</td><td className="border px-1 py-1">{x.cliente}</td><td className="border px-1 py-1">{x.produtoCod}</td><td className="border px-1 py-1">{x.produto}</td><td className="border px-1 py-1 text-right">{number(x.quantidade)}</td><td className="border px-1 py-1 text-right">{money(x.faturamento)}</td><td className="border px-1 py-1 text-right">{money(x.frete)}</td><td className="border px-1 py-1 text-right">{pct(x.percentual)}</td><td className="border px-1 py-1">{x.placa}</td><td className="border px-1 py-1">{x.data}</td><td className="border px-1 py-1 text-right">{money(x.freteUnit)}</td><td className="border px-1 py-1">{x.municipio}</td></tr>)}</tbody></table></Pos></>}
  </div></div>
 </div></Layout>
}
function CommonSlicers(p:any){return <><DateSlicer x={825.7} y={15.1} w={221.3} h={49.3} from={p.from} to={p.to} setFrom={p.setFrom} setTo={p.setTo}/><SearchableSlicer x={1139.5} y={15.1} w={123.7} h={49.3} value={p.placa} onChange={p.setPlaca} options={p.plateOpts} placeholder="Placa"/><SearchableSlicer x={868.1} y={88.9} w={226.2} h={49.4} value={p.clienteId} onChange={p.setClienteId} options={p.clientOpts} placeholder="Cliente"/><SearchableSlicer x={1159.9} y={89.8} w={103.2} h={48.5} value={p.produtoId} onChange={p.setProdutoId} options={p.productOpts} placeholder="Produto"/></>}
function VehiclePage(p:any){const top=p.byVehicle[0]?.name||"—";const avg=p.byVehicle.length?p.byVehicle.reduce((s:any,x:any)=>s+x.b,0)/p.byVehicle.length:0;const qty=p.filtered.reduce((s:number,x:Fact)=>s+x.quantidade,0),unit=qty?p.filtered.reduce((s:number,x:Fact)=>s+x.frete,0)/qty:0,avgQty=p.byVehicle.length?qty/p.byVehicle.length:0;return <><Title x={75.6} y={14.9} w={343.9} h={49.6} size={20}>Análise por Veículo</Title><Title x={24.2} y={80.8} w={167.9} h={31.4}>Veículo Maior Frete</Title><Title x={231.6} y={80.8} w={146.3} h={31.4}>Frete Médio Placa</Title><Title x={430} y={80.8} w={147.2} h={31.4}>Frete por Unidade</Title><Title x={625.7} y={80.8} w={150.8} h={31.4}>Qntd. Média Placa</Title><Title x={287.3} y={193.9} w={233.4} h={31.4}>Evolução do Frete por Veículo</Title><Title x={931} y={149.9} w={210.1} h={31.4}>Detalhamento por Veículo</Title><Title x={448.9} y={429.1} w={274.7} h={31.4}>Faturamento e % Frete por Veículo</Title><CommonSlicers {...p}/><CardValue x={11.7} y={116.7} w={193} h={70} value={top}/><CardValue x={206.5} y={112.2} w={197.5} h={74.5} value={money(avg)}/><CardValue x={404} y={112.2} w={198.4} h={74.5} value={money(unit)}/><CardValue x={602.4} y={112.2} w={196.6} h={74.5} value={number(avgQty)}/><Pos x={15.3} y={226.2} w={776.6} h={194.8}><ResponsiveContainer><LineChart data={p.byMonth} margin={{top:10,right:10,bottom:20,left:0}}><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis tick={{fontSize:9}}/><Tooltip contentStyle={tooltipStyle} formatter={moneyTooltip}/><Line type="monotone" dataKey="b" name="Frete Total" stroke={BLUE} strokeWidth={2}/></LineChart></ResponsiveContainer></Pos><SimpleTable x={806.6} y={187.1} w={458.6} h={164.9} headers={['Placa','Faturamento','Frete','%']} rows={p.byVehicle.slice(0,6).map((r:any)=>[r.name,money(r.a),money(r.b),pct(r.percent)])}/><Pos x={15.3} y={460.5} w={1249.7} h={242.4}><ResponsiveContainer><ComposedChart data={p.byVehicle.slice(0,12)} margin={{top:15,right:25,bottom:30,left:10}}><XAxis dataKey="name" tick={{fontSize:9}}/><YAxis yAxisId="left" tick={{fontSize:9}}/><YAxis yAxisId="right" orientation="right" tick={{fontSize:9}}/><Tooltip contentStyle={tooltipStyle} formatter={moneyTooltip}/><Legend verticalAlign="bottom"/><Bar yAxisId="left" dataKey="a" name="Faturamento" fill={BLUE}/><Line yAxisId="right" dataKey="percent" name="% Frete/Faturamento" stroke={DARK} strokeWidth={2}/></ComposedChart></ResponsiveContainer></Pos></>}
function SimpleTable({x,y,w,h,headers,rows}:{x:number;y:number;w:number;h:number;headers:string[];rows:string[][]}){return <Pos x={x} y={y} w={w} h={h} className="overflow-auto"><table className="w-full border-collapse bg-white text-[9px]"><thead><tr className="bg-[#0A508E] text-white">{headers.map(h=><th key={h} className="border border-[#0A508E] px-1 py-1.5 text-left">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="odd:bg-[#F5F7FA]">{r.map((v,j)=><td key={j} className="border px-1 py-1">{v}</td>)}</tr>)}</tbody></table></Pos>}
