import Layout from "@/components/Layout";
import {api} from "@/lib/api";
import {useClientes} from "@/lib/store";
import {useEffect,useMemo,useState} from "react";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Dialog,DialogContent,DialogHeader,DialogTitle} from "@/components/ui/dialog";
import {BriefcaseBusiness,Calculator,FileSignature,Plus,ReceiptText,Trash2} from "lucide-react";
import {toast} from "sonner";
const money=(v:number)=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});const today=()=>new Date().toISOString().slice(0,10);
type Proposta={id:string;codigo:string;clienteId:string;origem:string;destino:string;distanciaKm:number;valorFrete:number;custoEstimado:number;margemPrevista:number;status:string;validade?:string|null};
type Tabela={id:string;clienteId?:string|null;origem:string;destino:string;valorFrete:number;valorKm:number;vigenciaInicio:string;vigenciaFim?:string|null};
type Contrato={id:string;numero:string;clienteId:string;inicio:string;fim?:string|null;status:string;indiceReajuste:string};
export default function ComercialCRM(){const{items:clientes}=useClientes();const[tab,setTab]=useState<"PROPOSTAS"|"TABELAS"|"CONTRATOS">("PROPOSTAS");const[propostas,setPropostas]=useState<Proposta[]>([]);const[tabelas,setTabelas]=useState<Tabela[]>([]);const[contratos,setContratos]=useState<Contrato[]>([]);const[dash,setDash]=useState<any>({});const[modal,setModal]=useState<""|"PROPOSTA"|"TABELA"|"CONTRATO">("");const[form,setForm]=useState<any>({});const clienteNome=(id?:string|null)=>clientes.find(c=>c.id===id)?.nomeFantasia||clientes.find(c=>c.id===id)?.razaoSocial||"—";
 const load=async()=>{const[a,b,c,d]=await Promise.all([api.get("/comercial/dashboard"),api.get("/comercial/propostas"),api.get("/comercial/tabelas"),api.get("/comercial/contratos")]);setDash(a.data);setPropostas(b.data);setTabelas(c.data);setContratos(d.data)};useEffect(()=>{void load()},[]);
 const abrir=(m:typeof modal)=>{setForm({vigenciaInicio:today(),inicio:today(),status:m==="PROPOSTA"?"RASCUNHO":"ATIVO"});setModal(m)};
 const salvar=async()=>{try{if(modal==="PROPOSTA"){if(!form.clienteId)return toast.error("Selecione o cliente.");await api.post("/comercial/propostas",form)}if(modal==="TABELA")await api.post("/comercial/tabelas",form);if(modal==="CONTRATO"){if(!form.clienteId)return toast.error("Selecione o cliente.");await api.post("/comercial/contratos",form)}setModal("");toast.success("Registro comercial salvo.");await load()}catch(e:any){toast.error(e.response?.data?.message||"Não foi possível salvar.")}};
 const excluir=async(url:string)=>{if(!confirm("Excluir este registro?"))return;await api.delete(url);await load()};
 const margem=form.valorFrete?((Number(form.valorFrete)-Number(form.custoEstimado||0))/Number(form.valorFrete))*100:0;
 return <Layout><div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Comercial / CRM</h1><p className="text-sm text-muted-foreground">Propostas, tabelas de frete, contratos e margem prevista antes da viagem.</p></div><Button onClick={()=>abrir(tab==="PROPOSTAS"?"PROPOSTA":tab==="TABELAS"?"TABELA":"CONTRATO")}><Plus className="mr-2 h-4 w-4"/>Novo registro</Button></div>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[BriefcaseBusiness,"Propostas abertas",dash.propostasAbertas||0],[ReceiptText,"Em negociação",money(dash.valorEmNegociacao||0)],[FileSignature,"Contratos ativos",dash.contratosAtivos||0],[Calculator,"Tabelas de frete",dash.tabelasAtivas||0]].map(([Icon,l,v]:any)=><Card key={l}><CardContent className="p-4"><div className="flex justify-between text-xs text-muted-foreground"><span>{l}</span><Icon className="h-4 w-4"/></div><div className="mt-2 text-xl font-bold">{v}</div></CardContent></Card>)}</div>
 <div className="flex gap-2 border-b">{[["PROPOSTAS","Propostas"],["TABELAS","Tabelas de Frete"],["CONTRATOS","Contratos"]].map(([k,l])=><Button key={k} variant={tab===k?"default":"ghost"} onClick={()=>setTab(k as any)}>{l}</Button>)}</div>
 <Card><CardContent className="overflow-x-auto p-4">{tab==="PROPOSTAS"&&<table className="w-full min-w-[950px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="pb-2">Proposta</th><th>Cliente</th><th>Rota</th><th className="text-right">Frete</th><th className="text-right">Custo</th><th className="text-right">Margem</th><th>Status</th><th/></tr></thead><tbody>{propostas.map(x=><tr key={x.id} className="border-b"><td className="py-3 font-medium">{x.codigo}</td><td>{clienteNome(x.clienteId)}</td><td>{x.origem} → {x.destino}</td><td className="text-right">{money(x.valorFrete)}</td><td className="text-right">{money(x.custoEstimado)}</td><td className="text-right font-semibold">{x.margemPrevista.toFixed(1)}%</td><td>{x.status}</td><td className="text-right"><Button size="icon" variant="ghost" onClick={()=>excluir(`/comercial/propostas/${x.id}`)}><Trash2 className="h-4 w-4"/></Button></td></tr>)}</tbody></table>}
 {tab==="TABELAS"&&<table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="pb-2">Cliente</th><th>Origem</th><th>Destino</th><th className="text-right">Frete</th><th className="text-right">R$/km</th><th>Vigência</th><th/></tr></thead><tbody>{tabelas.map(x=><tr key={x.id} className="border-b"><td className="py-3">{x.clienteId?clienteNome(x.clienteId):"Tabela padrão"}</td><td>{x.origem||"—"}</td><td>{x.destino||"—"}</td><td className="text-right">{money(x.valorFrete)}</td><td className="text-right">{money(x.valorKm)}</td><td>{x.vigenciaInicio}{x.vigenciaFim?` a ${x.vigenciaFim}`:""}</td><td className="text-right"><Button size="icon" variant="ghost" onClick={()=>excluir(`/comercial/tabelas/${x.id}`)}><Trash2 className="h-4 w-4"/></Button></td></tr>)}</tbody></table>}
 {tab==="CONTRATOS"&&<table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="pb-2">Contrato</th><th>Cliente</th><th>Início</th><th>Fim</th><th>Reajuste</th><th>Status</th><th/></tr></thead><tbody>{contratos.map(x=><tr key={x.id} className="border-b"><td className="py-3 font-medium">{x.numero}</td><td>{clienteNome(x.clienteId)}</td><td>{x.inicio}</td><td>{x.fim||"Indeterminado"}</td><td>{x.indiceReajuste||"—"}</td><td>{x.status}</td><td className="text-right"><Button size="icon" variant="ghost" onClick={()=>excluir(`/comercial/contratos/${x.id}`)}><Trash2 className="h-4 w-4"/></Button></td></tr>)}</tbody></table>}</CardContent></Card>
 <Dialog open={!!modal} onOpenChange={o=>!o&&setModal("")}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>{modal==="PROPOSTA"?"Nova proposta":modal==="TABELA"?"Nova tabela de frete":"Novo contrato"}</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2">{modal!=="TABELA"&&<label className="text-sm sm:col-span-2">Cliente<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.clienteId||""} onChange={e=>setForm({...form,clienteId:e.target.value})}><option value="">Selecione</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nomeFantasia||c.razaoSocial}</option>)}</select></label>}{modal==="TABELA"&&<label className="text-sm sm:col-span-2">Cliente (opcional)<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.clienteId||""} onChange={e=>setForm({...form,clienteId:e.target.value})}><option value="">Tabela padrão</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nomeFantasia||c.razaoSocial}</option>)}</select></label>}
 {modal==="PROPOSTA"&&<><Field l="Origem" v={form.origem} set={(v:string)=>setForm({...form,origem:v})}/><Field l="Destino" v={form.destino} set={(v:string)=>setForm({...form,destino:v})}/><Field l="Distância (km)" type="number" v={form.distanciaKm} set={(v:string)=>setForm({...form,distanciaKm:Number(v)})}/><Field l="Frete proposto" type="number" v={form.valorFrete} set={(v:string)=>setForm({...form,valorFrete:Number(v)})}/><Field l="Custo estimado" type="number" v={form.custoEstimado} set={(v:string)=>setForm({...form,custoEstimado:Number(v)})}/><div className="rounded-lg border p-3"><div className="text-xs text-muted-foreground">Margem prevista</div><div className="text-xl font-bold">{margem.toFixed(1)}%</div></div><Field l="Validade" type="date" v={form.validade} set={(v:string)=>setForm({...form,validade:v})}/></>}
 {modal==="TABELA"&&<><Field l="Origem" v={form.origem} set={(v:string)=>setForm({...form,origem:v})}/><Field l="Destino" v={form.destino} set={(v:string)=>setForm({...form,destino:v})}/><Field l="Frete fixo" type="number" v={form.valorFrete} set={(v:string)=>setForm({...form,valorFrete:Number(v)})}/><Field l="Valor por km" type="number" v={form.valorKm} set={(v:string)=>setForm({...form,valorKm:Number(v)})}/><Field l="Início vigência" type="date" v={form.vigenciaInicio} set={(v:string)=>setForm({...form,vigenciaInicio:v})}/><Field l="Fim vigência" type="date" v={form.vigenciaFim} set={(v:string)=>setForm({...form,vigenciaFim:v})}/></>}
 {modal==="CONTRATO"&&<><Field l="Número (opcional)" v={form.numero} set={(v:string)=>setForm({...form,numero:v})}/><Field l="Início" type="date" v={form.inicio} set={(v:string)=>setForm({...form,inicio:v})}/><Field l="Fim" type="date" v={form.fim} set={(v:string)=>setForm({...form,fim:v})}/><Field l="Índice de reajuste" v={form.indiceReajuste} set={(v:string)=>setForm({...form,indiceReajuste:v})}/></>}</div><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setModal("")}>Cancelar</Button><Button onClick={salvar}>Salvar</Button></div></DialogContent></Dialog></div></Layout>}
function Field({l,v,set,type="text"}:{l:string;v:any;set:(v:string)=>void;type?:string}){return <label className="text-sm">{l}<Input className="mt-1" type={type} value={v??""} onChange={e=>set(e.target.value)}/></label>}
