import Layout from "@/components/Layout";
import {api} from "@/lib/api";
import {useVeiculos,useEstoqueProdutos} from "@/lib/store";
import {useEffect,useMemo,useState} from "react";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
import {Button} from "@/components/ui/button";import{Input}from"@/components/ui/input";
import{Dialog,DialogContent,DialogHeader,DialogTitle}from"@/components/ui/dialog";
import{Wrench,ClipboardList,AlertTriangle,FileText,Plus,CheckCircle2,Trash2}from"lucide-react";import{toast}from"sonner";
const today=()=>new Date().toISOString().slice(0,10);const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
type Plano={id:string;veiculoId:string;nome:string;categoria:string;intervaloKm?:number|null;proximoKm?:number|null;proximaData?:string|null;ativo:boolean};
type OS={id:string;numero:string;veiculoId:string;tipo:string;status:string;descricao:string;fornecedor:string;dataAbertura:string;valorTotal:number};
type Doc={id:string;veiculoId:string;tipo:string;numero:string;validade?:string|null};
export default function Manutencao(){const{items:veiculos}=useVeiculos();const{items:produtosEstoque}=useEstoqueProdutos();const[tab,setTab]=useState<"OS"|"PLANOS"|"DOCS">("OS");const[dash,setDash]=useState<any>({});const[planos,setPlanos]=useState<Plano[]>([]);const[ordens,setOrdens]=useState<OS[]>([]);const[docs,setDocs]=useState<Doc[]>([]);const[modal,setModal]=useState<""|"OS"|"PLANO"|"DOC">("");const[form,setForm]=useState<any>({});
const placa=(id:string)=>veiculos.find(v=>v.id===id)?.placa||"—";const load=async()=>{try{const[a,b,c,d]=await Promise.all([api.get("/manutencao/dashboard"),api.get("/manutencao/planos"),api.get("/manutencao/ordens"),api.get("/manutencao/documentos")]);setDash(a.data);setPlanos(b.data);setOrdens(c.data);setDocs(d.data)}catch(e:any){toast.error(e.response?.data?.message||"Erro ao carregar manutenção")}};useEffect(()=>{void load()},[]);
const abrir=(x:"OS"|"PLANO"|"DOC")=>{setForm({dataAbertura:today(),categoria:"PREVENTIVA",tipo:"PREVENTIVA"});setModal(x)};
const salvar=async()=>{if(!form.veiculoId)return toast.error("Selecione o veículo.");if(modal==="OS"){if(!form.descricao)return toast.error("Informe a descrição.");await api.post("/manutencao/ordens",{...form,itens:form.produtoId?[{produtoId:form.produtoId,quantidade:Number(form.quantidadePeca)||1,valorUnitario:Number(form.valorUnitarioPeca)||0}]:[]})}else if(modal==="PLANO"){if(!form.nome)return toast.error("Informe o serviço.");await api.post("/manutencao/planos",form)}else{if(!form.tipo)return toast.error("Informe o documento.");await api.post("/manutencao/documentos",form)}setModal("");toast.success("Registro salvo.");await load()};
const concluir=async(x:OS)=>{await api.put(`/manutencao/ordens/${x.id}/concluir`,{dataConclusao:today()});toast.success("OS concluída e custo enviado ao Financeiro.");await load()};
return <Layout><div className="space-y-6 p-4 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Frota e Manutenção</h1><p className="text-sm text-muted-foreground">Preventivas, corretivas, ordens de serviço e vencimentos da frota.</p></div><Button onClick={()=>abrir(tab==="OS"?"OS":tab==="PLANOS"?"PLANO":"DOC")}><Plus className="mr-2 h-4 w-4"/>Novo {tab==="OS"?"OS":tab==="PLANOS"?"plano":"documento"}</Button></div>
<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[Wrench,"OS abertas",dash.osAbertas||0],[ClipboardList,"Planos ativos",dash.planosAtivos||0],[AlertTriangle,"Alertas",dash.alertas?.length||0],[FileText,"Custo manutenção",money(dash.custoTotal||0)]].map(([Icon,l,v]:any)=><Card key={l}><CardContent className="p-4"><div className="flex justify-between text-xs text-muted-foreground"><span>{l}</span><Icon className="h-4 w-4"/></div><div className="mt-2 text-xl font-bold">{v}</div></CardContent></Card>)}</div>
{dash.alertas?.length>0&&<Card><CardHeader><CardTitle className="text-base">Alertas da frota</CardTitle></CardHeader><CardContent className="grid gap-2 md:grid-cols-2">{dash.alertas.slice(0,8).map((a:any,i:number)=><div key={i} className="rounded-lg border p-3"><div className="font-medium">{placa(a.veiculoId)} · {a.titulo}</div><div className="text-xs text-muted-foreground">{a.detalhe}</div></div>)}</CardContent></Card>}
<div className="flex gap-2 border-b">{[["OS","Ordens de Serviço"],["PLANOS","Preventivas"],["DOCS","Documentos"]].map(([k,l])=><Button key={k} variant={tab===k?"default":"ghost"} onClick={()=>setTab(k as any)}>{l}</Button>)}</div>
<Card><CardContent className="overflow-x-auto p-4">
{tab==="OS"&&<table className="w-full min-w-[800px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="pb-2">OS</th><th>Veículo</th><th>Tipo</th><th>Descrição</th><th>Status</th><th className="text-right">Custo</th><th/></tr></thead><tbody>{ordens.map(x=><tr className="border-b" key={x.id}><td className="py-3 font-medium">{x.numero}</td><td>{placa(x.veiculoId)}</td><td>{x.tipo}</td><td>{x.descricao}</td><td>{x.status}</td><td className="text-right">{money(x.valorTotal)}</td><td className="text-right">{x.status!=="CONCLUIDA"&&<Button size="sm" variant="outline" onClick={()=>concluir(x)}><CheckCircle2 className="mr-1 h-4 w-4"/>Concluir</Button>}</td></tr>)}</tbody></table>}
{tab==="PLANOS"&&<table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="pb-2">Veículo</th><th>Serviço</th><th>Intervalo</th><th>Próximo KM</th><th>Próxima data</th><th/></tr></thead><tbody>{planos.map(x=><tr className="border-b" key={x.id}><td className="py-3">{placa(x.veiculoId)}</td><td className="font-medium">{x.nome}</td><td>{x.intervaloKm?`${x.intervaloKm} km`:"—"}</td><td>{x.proximoKm??"—"}</td><td>{x.proximaData||"—"}</td><td className="text-right"><Button size="icon" variant="ghost" onClick={async()=>{await api.delete(`/manutencao/planos/${x.id}`);await load()}}><Trash2 className="h-4 w-4"/></Button></td></tr>)}</tbody></table>}
{tab==="DOCS"&&<table className="w-full min-w-[650px] text-sm"><thead><tr className="border-b text-left text-muted-foreground"><th className="pb-2">Veículo</th><th>Documento</th><th>Número</th><th>Validade</th><th/></tr></thead><tbody>{docs.map(x=><tr className="border-b" key={x.id}><td className="py-3">{placa(x.veiculoId)}</td><td className="font-medium">{x.tipo}</td><td>{x.numero||"—"}</td><td>{x.validade||"—"}</td><td className="text-right"><Button size="icon" variant="ghost" onClick={async()=>{await api.delete(`/manutencao/documentos/${x.id}`);await load()}}><Trash2 className="h-4 w-4"/></Button></td></tr>)}</tbody></table>}
</CardContent></Card>
<Dialog open={!!modal} onOpenChange={o=>!o&&setModal("")}><DialogContent><DialogHeader><DialogTitle>{modal==="OS"?"Nova Ordem de Serviço":modal==="PLANO"?"Novo plano preventivo":"Novo documento da frota"}</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm sm:col-span-2">Veículo<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.veiculoId||""} onChange={e=>setForm({...form,veiculoId:e.target.value})}><option value="">Selecione</option>{veiculos.map(v=><option key={v.id} value={v.id}>{v.placa} {v.modelo?`· ${v.modelo}`:""}</option>)}</select></label>
{modal==="OS"&&<><label className="text-sm">Tipo<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.tipo||"PREVENTIVA"} onChange={e=>setForm({...form,tipo:e.target.value})}><option>PREVENTIVA</option><option>CORRETIVA</option></select></label><label className="text-sm">Data<Input className="mt-1" type="date" value={form.dataAbertura||today()} onChange={e=>setForm({...form,dataAbertura:e.target.value})}/></label><label className="text-sm sm:col-span-2">Descrição<Input className="mt-1" value={form.descricao||""} onChange={e=>setForm({...form,descricao:e.target.value})}/></label><label className="text-sm">Fornecedor<Input className="mt-1" value={form.fornecedor||""} onChange={e=>setForm({...form,fornecedor:e.target.value})}/></label><label className="text-sm">KM abertura<Input className="mt-1" type="number" value={form.kmAbertura||""} onChange={e=>setForm({...form,kmAbertura:Number(e.target.value)})}/></label><label className="text-sm sm:col-span-2">Peça do Almoxarifado<select className="mt-1 h-10 w-full rounded-md border bg-background px-3" value={form.produtoId||""} onChange={e=>setForm({...form,produtoId:e.target.value})}><option value="">Sem baixa automática de peça</option>{produtosEstoque.map(p=><option key={p.id} value={p.id}>{p.codigoInterno} · {p.nome}</option>)}</select></label><label className="text-sm">Quantidade da peça<Input className="mt-1" type="number" step="0.001" value={form.quantidadePeca||""} onChange={e=>setForm({...form,quantidadePeca:e.target.value})}/></label><label className="text-sm">Valor unitário da peça<Input className="mt-1" type="number" step="0.01" value={form.valorUnitarioPeca||""} onChange={e=>setForm({...form,valorUnitarioPeca:e.target.value})}/></label><label className="text-sm">Peças avulsas (R$)<Input className="mt-1" type="number" value={form.valorPecas||""} onChange={e=>setForm({...form,valorPecas:Number(e.target.value)})}/></label><label className="text-sm">Mão de obra<Input className="mt-1" type="number" value={form.valorMaoObra||""} onChange={e=>setForm({...form,valorMaoObra:Number(e.target.value)})}/></label></>}
{modal==="PLANO"&&<><label className="text-sm sm:col-span-2">Serviço<Input className="mt-1" placeholder="Ex.: Troca de óleo" value={form.nome||""} onChange={e=>setForm({...form,nome:e.target.value})}/></label><label className="text-sm">Intervalo KM<Input className="mt-1" type="number" value={form.intervaloKm||""} onChange={e=>setForm({...form,intervaloKm:Number(e.target.value)})}/></label><label className="text-sm">Último KM<Input className="mt-1" type="number" value={form.ultimoKm||""} onChange={e=>setForm({...form,ultimoKm:Number(e.target.value)})}/></label><label className="text-sm">Próxima data<Input className="mt-1" type="date" value={form.proximaData||""} onChange={e=>setForm({...form,proximaData:e.target.value})}/></label></>}
{modal==="DOC"&&<><label className="text-sm">Tipo<Input className="mt-1" placeholder="CRLV, Seguro..." value={form.tipo||""} onChange={e=>setForm({...form,tipo:e.target.value})}/></label><label className="text-sm">Número<Input className="mt-1" value={form.numero||""} onChange={e=>setForm({...form,numero:e.target.value})}/></label><label className="text-sm">Validade<Input className="mt-1" type="date" value={form.validade||""} onChange={e=>setForm({...form,validade:e.target.value})}/></label></>}</div><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setModal("")}>Cancelar</Button><Button onClick={salvar}>Salvar</Button></div></DialogContent></Dialog></div></Layout>}
