import { Router } from "express";
import { asyncHandler } from "../utils/async-handler.js";
import { validate } from "../middlewares/validate.js";
import { bodySchema, idParamsSchema, partialBodySchema, lancamentoFinanceiroBody } from "../validators/schemas.js";
import { financeiroController } from "../controllers/financeiro.controller.js";
export const financeiroRoutes = Router();
financeiroRoutes.get("/resumo/dre", asyncHandler(financeiroController.resumo));
financeiroRoutes.get("/analise/rentabilidade", asyncHandler(financeiroController.analise));
financeiroRoutes.get("/fluxo-caixa", asyncHandler(financeiroController.fluxo));
financeiroRoutes.get("/baixas", asyncHandler(financeiroController.baixas));
financeiroRoutes.post("/:id/baixas", validate(idParamsSchema), asyncHandler(financeiroController.adicionarBaixa));
financeiroRoutes.delete("/baixas/:id", validate(idParamsSchema), asyncHandler(financeiroController.removerBaixa));
financeiroRoutes.delete("/todos", asyncHandler(financeiroController.removeAll));
financeiroRoutes.get("/", asyncHandler(financeiroController.list));
financeiroRoutes.get("/:id", validate(idParamsSchema), asyncHandler(financeiroController.get));
financeiroRoutes.post("/", validate(bodySchema(lancamentoFinanceiroBody)), asyncHandler(financeiroController.create));
financeiroRoutes.put("/:id", validate(partialBodySchema(lancamentoFinanceiroBody)), asyncHandler(financeiroController.update));
financeiroRoutes.delete("/:id", validate(idParamsSchema), asyncHandler(financeiroController.remove));
