ALTER TABLE "motoristas"
  ADD COLUMN IF NOT EXISTS "rg" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "dataNascimento" DATE,
  ADD COLUMN IF NOT EXISTS "telefone" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "email" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "endereco" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "cidade" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "uf" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "cep" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "dataAdmissao" DATE,
  ADD COLUMN IF NOT EXISTS "cnhNumero" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "cnhRegistro" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "cnhCategoria" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "cnhValidade" DATE,
  ADD COLUMN IF NOT EXISTS "primeiraHabilitacao" DATE,
  ADD COLUMN IF NOT EXISTS "moppValidade" DATE,
  ADD COLUMN IF NOT EXISTS "toxicologicoValidade" DATE,
  ADD COLUMN IF NOT EXISTS "observacoes" TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS "motoristas_cpf_idx" ON "motoristas"("cpf");
CREATE INDEX IF NOT EXISTS "motoristas_cnhValidade_idx" ON "motoristas"("cnhValidade");

ALTER TABLE "veiculos"
  ADD COLUMN IF NOT EXISTS "marca" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "renavam" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "chassi" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "anoFabricacao" INTEGER,
  ADD COLUMN IF NOT EXISTS "anoModelo" INTEGER,
  ADD COLUMN IF NOT EXISTS "cor" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "combustivel" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "proprietario" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "crlvValidade" DATE,
  ADD COLUMN IF NOT EXISTS "ipvaVencimento" DATE,
  ADD COLUMN IF NOT EXISTS "ipvaPago" BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS "licenciamentoVencimento" DATE,
  ADD COLUMN IF NOT EXISTS "seguroValidade" DATE,
  ADD COLUMN IF NOT EXISTS "rntrc" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "observacoes" TEXT NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS "veiculos_renavam_idx" ON "veiculos"("renavam");
CREATE INDEX IF NOT EXISTS "veiculos_crlvValidade_idx" ON "veiculos"("crlvValidade");
CREATE INDEX IF NOT EXISTS "veiculos_ipvaVencimento_idx" ON "veiculos"("ipvaVencimento");
