import { useMemo, useRef, useState, type ReactNode } from "react";
import { useMotoristas, useVeiculos, useViagens, type Motorista, type StatusMotorista } from "@/lib/store";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Card, CardContent } from "@/components/ui/card";
import DataTable from "./DataTable";
import { Plus, User, UserCheck, UserX, AlertTriangle, BadgeCheck, Clock3, FileText, UploadCloud, Eye, Trash2, Palmtree } from "lucide-react";
import { toast } from "sonner";

interface FormState {
  nome:string; cpf:string; rg:string; dataNascimento:string; telefone:string; email:string; endereco:string; cidade:string; uf:string; cep:string;
  salarioBase:string; dataAdmissao:string; cnhNumero:string; cnhRegistro:string; cnhCategoria:string; cnhValidade:string; cnhEmissao:string;
  primeiraHabilitacao:string; moppValidade:string; toxicologicoValidade:string; observacoes:string;
}
type StatusFilter = "TODOS" | StatusMotorista;
const emptyForm:FormState={nome:"",cpf:"",rg:"",dataNascimento:"",telefone:"",email:"",endereco:"",cidade:"",uf:"",cep:"",salarioBase:"",dataAdmissao:"",cnhNumero:"",cnhRegistro:"",cnhCategoria:"",cnhValidade:"",cnhEmissao:"",primeiraHabilitacao:"",moppValidade:"",toxicologicoValidade:"",observacoes:""};
const daysUntil=(date?:string|null)=>{if(!date)return null;const a=new Date(`${date}T00:00:00`),b=new Date();b.setHours(0,0,0,0);return Math.ceil((a.getTime()-b.getTime())/86400000)};
const dateStatus=(date?:string|null)=>{const d=daysUntil(date);if(d===null)return "SEM_DATA";if(d<0)return "VENCIDO";if(d<=30)return "ATENCAO";return "OK"};
const dateLabel=(v?:string|null)=>v?v.split("-").reverse().join("/"):"—";

export default function MotoristaTab(){
 const{items,create,update,refresh}=useMotoristas();const{items:veiculos}=useVeiculos();const{items:viagens}=useViagens();const[open,setOpen]=useState(false);const[editingId,setEditingId]=useState<string|null>(null);const[form,setForm]=useState<FormState>(emptyForm);const[statusFilter,setStatusFilter]=useState<StatusFilter>("TODOS");const[query,setQuery]=useState("");const[saving,setSaving]=useState(false);const[cnhFile,setCnhFile]=useState<File|null>(null);const[toxicologicoFile,setToxicologicoFile]=useState<File|null>(null);
 const alertas=useMemo(()=>items.filter(x=>x.status==="ATIVO").flatMap(x=>[
   {motorista:x,tipo:"CNH",data:x.cnhValidade,status:dateStatus(x.cnhValidade)},
   {motorista:x,tipo:"MOPP",data:x.moppValidade,status:dateStatus(x.moppValidade)},
   {motorista:x,tipo:"Toxicológico",data:x.toxicologicoValidade,status:dateStatus(x.toxicologicoValidade)},
 ]).filter(x=>x.status==="VENCIDO"||x.status==="ATENCAO").sort((a,b)=>(daysUntil(a.data)??99999)-(daysUntil(b.data)??99999)),[items]);
 const filteredItems=useMemo(()=>{const q=normalizeSearch(query).trim();return items.filter(x=>(statusFilter==="TODOS"||x.status===statusFilter)&&(!q||normalizeSearch([x.nome,x.cpf,x.rg,x.telefone,x.cidade,x.cnhNumero,x.cnhCategoria,x.status].join(" ")).includes(q)))},[items,query,statusFilter]);
 const ativos=items.filter(x=>x.status==="ATIVO").length;
 const veiculosPorMotorista=useMemo(()=>{const map=new Map<string,string[]>();for(const v of veiculos){if(!v.motoristaId)continue;const list=map.get(v.motoristaId)??[];if(v.placa&&!list.includes(v.placa))list.push(v.placa);map.set(v.motoristaId,list)}return map},[veiculos]);
 const viagensPorMotorista=useMemo(()=>{const map=new Map<string,{total:number;ativas:number;ultima?:string}>();for(const v of viagens){if(!v.motoristaId)continue;const current=map.get(v.motoristaId)??{total:0,ativas:0,ultima:undefined};current.total+=1;if(["PLANEJADA","CARREGANDO","EM_TRANSITO"].includes(v.status??""))current.ativas+=1;if(v.dataManifesto&&(!current.ultima||v.dataManifesto>current.ultima))current.ultima=v.dataManifesto;map.set(v.motoristaId,current)}return map},[viagens]);
 const handleOpenCreate=()=>{setForm(emptyForm);setEditingId(null);setCnhFile(null);setToxicologicoFile(null);setOpen(true)};
 const handleOpenEdit=(x:Motorista)=>{setCnhFile(null);setToxicologicoFile(null);setForm({nome:x.nome,cpf:x.cpf,rg:x.rg||"",dataNascimento:x.dataNascimento||"",telefone:x.telefone||"",email:x.email||"",endereco:x.endereco||"",cidade:x.cidade||"",uf:x.uf||"",cep:x.cep||"",salarioBase:String(x.salarioBase),dataAdmissao:x.dataAdmissao||"",cnhNumero:x.cnhNumero||"",cnhRegistro:x.cnhRegistro||"",cnhCategoria:x.cnhCategoria||"",cnhValidade:x.cnhValidade||"",cnhEmissao:x.cnhEmissao||"",primeiraHabilitacao:x.primeiraHabilitacao||"",moppValidade:x.moppValidade||"",toxicologicoValidade:x.toxicologicoValidade||"",observacoes:x.observacoes||""});setEditingId(x.id);setOpen(true)};
 const uploadDoc=async(id:string,tipo:"cnh"|"toxicologico",file:File|null)=>{if(!file)return;const fd=new FormData();fd.append("arquivo",file);await api.post(`/motoristas/${id}/documento/${tipo}`,fd,{headers:{"Content-Type":"multipart/form-data"}})};
 const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();if(saving)return;if(!form.nome.trim()||!form.cpf.trim())return toast.error("Preencha nome e CPF.");setSaving(true);try{const payload={...form,salarioBase:parseFloat(form.salarioBase)||0,uf:form.uf.toUpperCase().slice(0,2),status:"ATIVO" as StatusMotorista};let saved:Motorista;if(editingId){const current=items.find(x=>x.id===editingId);saved=await update(editingId,{...payload,status:current?.status||"ATIVO"})}else saved=await create(payload);await uploadDoc(saved.id,"cnh",cnhFile);await uploadDoc(saved.id,"toxicologico",toxicologicoFile);if(cnhFile||toxicologicoFile)await refresh();toast.success(editingId?"Motorista atualizado!":"Motorista cadastrado!");setOpen(false)}catch(error:any){toast.error(error?.response?.data?.message??"Não foi possível salvar o motorista.")}finally{setSaving(false)}};
 const toggle=async(x:Motorista)=>{const status:StatusMotorista=x.status==="DEMITIDO"?"ATIVO":"DEMITIDO";if(!confirm(`${status==="DEMITIDO"?"Demitir":"Reativar"} ${x.nome}?`))return;await update(x.id,{status})};
 const toggleFerias=async(x:Motorista)=>{if(x.status==="DEMITIDO")return;const status:StatusMotorista=x.status==="FERIAS"?"ATIVO":"FERIAS";if(!confirm(`${status==="FERIAS"?"Colocar":"Retirar"} ${x.nome} ${status==="FERIAS"?"de férias":"das férias"}?`))return;await update(x.id,{status});toast.success(status==="FERIAS"?`${x.nome} marcado como em férias.`:`${x.nome} retornou das férias.`)};
 const columns:any[]=[
  {key:"nome",label:"Motorista",render:(x:Motorista)=><div><div className="flex items-center gap-2 font-medium"><User className="h-4 w-4"/>{x.nome}</div><div className="text-xs text-muted-foreground">{x.telefone||x.cpf}</div></div>},
  {key:"cnh",label:"CNH",render:(x:Motorista)=><div><div className="font-medium">{x.cnhNumero||"—"} {x.cnhCategoria?`· ${x.cnhCategoria}`:""}</div><Validity date={x.cnhValidade}/></div>},
  {key:"cidade",label:"Cidade",render:(x:Motorista)=><span>{x.cidade?`${x.cidade}${x.uf?`/${x.uf}`:""}`:"—"}</span>},
  {key:"veiculo",label:"Veículo / placa",render:(x:Motorista)=>{const placas=veiculosPorMotorista.get(x.id)??[];return placas.length?<div className="flex flex-wrap gap-1">{placas.map(placa=><span key={placa} className="rounded-md border bg-muted/40 px-2 py-1 text-xs font-medium">{placa}</span>)}</div>:<span className="text-muted-foreground">Sem veículo vinculado</span>}},
  {key:"viagens",label:"Acertos",render:(x:Motorista)=>{const info=viagensPorMotorista.get(x.id);if(!info)return <span className="text-muted-foreground">Nenhuma</span>;return <div><div className="font-medium">{info.total} viagem(ns)</div><div className="text-xs text-muted-foreground">{info.ativas>0?`${info.ativas} em andamento`:info.ultima?`Última ${dateLabel(info.ultima)}`:"Sem viagem ativa"}</div></div>}},
  {key:"salarioBase",label:"Salário",render:(x:Motorista)=><span>R$ {x.salarioBase.toFixed(2).replace(".",",")}</span>},
  {key:"status",label:"Status",render:(x:Motorista)=><span className={x.status==="ATIVO"?"rounded-full bg-green-100 px-2 py-1 text-xs font-semibold text-green-700":x.status==="FERIAS"?"rounded-full bg-amber-100 px-2 py-1 text-xs font-semibold text-amber-700":"rounded-full bg-red-100 px-2 py-1 text-xs font-semibold text-red-700"}>{x.status==="ATIVO"?"Ativo":x.status==="FERIAS"?"Férias":"Demitido"}</span>},
  {key:"situacao",label:"Ação",render:(x:Motorista)=><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={()=>toggle(x)}>{x.status==="DEMITIDO"?<UserCheck className="mr-1 h-4 w-4"/>:<UserX className="mr-1 h-4 w-4"/>}{x.status==="DEMITIDO"?"Reativar":"Demitir"}</Button>{x.status!=="DEMITIDO"&&<Button type="button" variant="outline" size="sm" onClick={()=>toggleFerias(x)}><Palmtree className="mr-1 h-4 w-4"/>{x.status==="FERIAS"?"Retornar":"Férias"}</Button>}</div>}
 ];
 return <div className="space-y-4">
  <div className="grid gap-3 sm:grid-cols-3">
   <Card><CardContent className="p-4"><div className="text-xs text-muted-foreground">Motoristas ativos</div><div className="mt-1 text-2xl font-bold">{ativos}</div></CardContent></Card>
   <Card><CardContent className="p-4"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>Documentos vencidos</span><AlertTriangle className="h-4 w-4"/></div><div className="mt-1 text-2xl font-bold">{alertas.filter(a=>a.status==="VENCIDO").length}</div></CardContent></Card>
   <Card><CardContent className="p-4"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>Vencem em 30 dias</span><Clock3 className="h-4 w-4"/></div><div className="mt-1 text-2xl font-bold">{alertas.filter(a=>a.status==="ATENCAO").length}</div></CardContent></Card>
  </div>
  {alertas.length>0&&<div className="rounded-xl border p-4"><div className="mb-3 flex items-center gap-2 font-semibold"><AlertTriangle className="h-4 w-4"/>Alertas de documentos</div><div className="grid gap-2 md:grid-cols-2">{alertas.slice(0,8).map((a,i)=><div key={`${a.motorista.id}-${a.tipo}-${i}`} className="rounded-lg border p-3 text-sm"><div className="font-medium">{a.motorista.nome} · {a.tipo}</div><div className={a.status==="VENCIDO"?"text-red-600":"text-amber-600"}>{a.status==="VENCIDO"?"Vencido":"Próximo do vencimento"} · {dateLabel(a.data)}</div></div>)}</div></div>}
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="flex flex-col gap-3 sm:flex-row"><div className="w-full sm:w-72"><Label>Pesquisar</Label><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome, CPF, CNH, cidade..."/></div><div className="w-full sm:w-44"><Label>Status</Label><Select value={statusFilter} onValueChange={v=>setStatusFilter(v as StatusFilter)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="TODOS">Todos</SelectItem><SelectItem value="ATIVO">Ativos</SelectItem><SelectItem value="FERIAS">Em férias</SelectItem><SelectItem value="DEMITIDO">Demitidos</SelectItem></SelectContent></Select></div></div><Button onClick={handleOpenCreate}><Plus className="mr-1 h-4 w-4"/>Novo Motorista</Button></div>
  <DataTable columns={columns} data={filteredItems} onEdit={handleOpenEdit} emptyMessage="Nenhum motorista encontrado."/>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-4xl overflow-y-auto"><DialogHeader><DialogTitle>{editingId?"Editar Motorista":"Novo Motorista"}</DialogTitle></DialogHeader><form onSubmit={handleSubmit} className="space-y-5">
   <Section title="Dados pessoais"><div className="grid gap-3 md:grid-cols-3"><Field label="Nome"><Input value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></Field><Field label="CPF"><Input value={form.cpf} onChange={e=>setForm({...form,cpf:e.target.value})}/></Field><Field label="RG"><Input value={form.rg} onChange={e=>setForm({...form,rg:e.target.value})}/></Field><Field label="Nascimento"><Input type="date" value={form.dataNascimento} onChange={e=>setForm({...form,dataNascimento:e.target.value})}/></Field><Field label="Telefone"><Input value={form.telefone} onChange={e=>setForm({...form,telefone:e.target.value})}/></Field><Field label="E-mail"><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field></div></Section>
   <Section title="Endereço"><div className="grid gap-3 md:grid-cols-4"><Field label="Endereço"><Input value={form.endereco} onChange={e=>setForm({...form,endereco:e.target.value})}/></Field><Field label="Cidade"><Input value={form.cidade} onChange={e=>setForm({...form,cidade:e.target.value})}/></Field><Field label="UF"><Input maxLength={2} value={form.uf} onChange={e=>setForm({...form,uf:e.target.value.toUpperCase()})}/></Field><Field label="CEP"><Input value={form.cep} onChange={e=>setForm({...form,cep:e.target.value})}/></Field></div></Section>
   <Section title="CNH e qualificações"><div className="grid gap-3 md:grid-cols-3"><Field label="Número CNH"><Input value={form.cnhNumero} onChange={e=>setForm({...form,cnhNumero:e.target.value})}/></Field><Field label="Registro CNH"><Input value={form.cnhRegistro} onChange={e=>setForm({...form,cnhRegistro:e.target.value})}/></Field><Field label="Categoria"><Input placeholder="Ex.: AE" value={form.cnhCategoria} onChange={e=>setForm({...form,cnhCategoria:e.target.value.toUpperCase()})}/></Field><Field label="Data de emissão da CNH"><Input type="date" value={form.cnhEmissao} onChange={e=>setForm({...form,cnhEmissao:e.target.value})}/></Field><Field label="Validade CNH"><Input type="date" value={form.cnhValidade} onChange={e=>setForm({...form,cnhValidade:e.target.value})}/></Field><Field label="1ª habilitação"><Input type="date" value={form.primeiraHabilitacao} onChange={e=>setForm({...form,primeiraHabilitacao:e.target.value})}/></Field><Field label="Validade MOPP"><Input type="date" value={form.moppValidade} onChange={e=>setForm({...form,moppValidade:e.target.value})}/></Field><Field label="Exame toxicológico"><Input type="date" value={form.toxicologicoValidade} onChange={e=>setForm({...form,toxicologicoValidade:e.target.value})}/></Field></div></Section>
   <Section title="Documentos em PDF"><div className="grid gap-3 md:grid-cols-2"><PdfDrop label="CNH em PDF" file={cnhFile} onFile={setCnhFile} storedName={editingId?items.find(x=>x.id===editingId)?.cnhPdfNome:undefined} stored={!!(editingId&&items.find(x=>x.id===editingId)?.cnhPdfStored)} onView={editingId?()=>window.open(`/api/motoristas/${editingId}/documento/cnh`,"_blank"):undefined} onRemove={editingId?async()=>{await api.delete(`/motoristas/${editingId}/documento/cnh`);await refresh();toast.success("PDF da CNH removido.")}:undefined}/><PdfDrop label="Exame toxicológico em PDF" file={toxicologicoFile} onFile={setToxicologicoFile} storedName={editingId?items.find(x=>x.id===editingId)?.toxicologicoPdfNome:undefined} stored={!!(editingId&&items.find(x=>x.id===editingId)?.toxicologicoPdfStored)} onView={editingId?()=>window.open(`/api/motoristas/${editingId}/documento/toxicologico`,"_blank"):undefined} onRemove={editingId?async()=>{await api.delete(`/motoristas/${editingId}/documento/toxicologico`);await refresh();toast.success("PDF do exame toxicológico removido.")}:undefined}/></div></Section>
   <Section title="Vínculo e observações"><div className="grid gap-3 md:grid-cols-2"><Field label="Data de admissão"><Input type="date" value={form.dataAdmissao} onChange={e=>setForm({...form,dataAdmissao:e.target.value})}/></Field><Field label="Salário Base (R$)"><Input type="number" step="0.01" value={form.salarioBase} onChange={e=>setForm({...form,salarioBase:e.target.value})}/></Field><Field label="Observações"><Input value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></Field></div></Section>
   <DialogFooter><Button type="submit" disabled={saving}>{saving?"Salvando...":editingId?"Salvar alterações":"Cadastrar"}</Button></DialogFooter>
  </form></DialogContent></Dialog>
 </div>
}
function Validity({date}:{date?:string|null}){const s=dateStatus(date);return <div className={s==="VENCIDO"?"text-xs text-red-600":s==="ATENCAO"?"text-xs text-amber-600":"text-xs text-muted-foreground"}>{date?`Validade ${dateLabel(date)}`:"Validade não informada"}</div>}
function Section({title,children}:{title:string;children:ReactNode}){return <div><div className="mb-2 flex items-center gap-2 text-sm font-semibold"><BadgeCheck className="h-4 w-4"/>{title}</div>{children}</div>}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="space-y-1"><Label>{label}</Label>{children}</div>}
function normalizeSearch(v:unknown){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLocaleLowerCase("pt-BR")}

function PdfDrop({label,file,onFile,storedName,stored,onView,onRemove}:{label:string;file:File|null;onFile:(f:File|null)=>void;storedName?:string;stored?:boolean;onView?:()=>void;onRemove?:()=>void|Promise<void>}){const input=useRef<HTMLInputElement|null>(null);const accept=(f?:File)=>{if(!f)return;if(f.type!=="application/pdf"&&!f.name.toLowerCase().endsWith(".pdf")){toast.error("Envie somente arquivo PDF.");return}if(f.size>10*1024*1024){toast.error("O PDF deve ter no máximo 10 MB.");return}onFile(f)};return <div className="space-y-2"><Label>{label}</Label><div onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add("border-primary")}} onDragLeave={e=>e.currentTarget.classList.remove("border-primary")} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove("border-primary");accept(e.dataTransfer.files?.[0])}} onClick={()=>input.current?.click()} className="cursor-pointer rounded-lg border-2 border-dashed p-4 text-center transition-colors hover:border-primary"><input ref={input} className="hidden" type="file" accept="application/pdf,.pdf" onChange={e=>accept(e.target.files?.[0])}/><UploadCloud className="mx-auto mb-2 h-5 w-5"/><div className="text-sm font-medium">{file?file.name:"Arraste o PDF aqui ou clique para selecionar"}</div><div className="mt-1 text-xs text-muted-foreground">Somente PDF · até 10 MB</div></div>{file&&<Button type="button" size="sm" variant="ghost" onClick={()=>onFile(null)}><Trash2 className="mr-1 h-4 w-4"/>Remover seleção</Button>}{stored&&!file&&<div className="flex flex-wrap items-center gap-2 rounded-md border p-2 text-sm"><FileText className="h-4 w-4"/><span className="min-w-0 flex-1 truncate">{storedName||"Documento cadastrado"}</span>{onView&&<Button type="button" size="sm" variant="outline" onClick={e=>{e.stopPropagation();onView()}}><Eye className="mr-1 h-4 w-4"/>Visualizar</Button>}{onRemove&&<Button type="button" size="sm" variant="ghost" onClick={async e=>{e.stopPropagation();if(confirm("Remover este PDF?"))await onRemove()}}><Trash2 className="h-4 w-4"/></Button>}</div>}</div>}
