import {useMemo,useRef,useState,type ReactNode}from"react";
import{useMotoristas,useVeiculos,type SubcategoriaVeiculo,type Veiculo}from"@/lib/store";import{api}from"@/lib/api";
import{Button}from"@/components/ui/button";import{Input}from"@/components/ui/input";import{Label}from"@/components/ui/label";
import{Select,SelectContent,SelectItem,SelectTrigger,SelectValue}from"@/components/ui/select";
import{Dialog,DialogContent,DialogHeader,DialogTitle,DialogFooter}from"@/components/ui/dialog";
import{Card,CardContent}from"@/components/ui/card";import DataTable from"./DataTable";import{Plus,Truck,AlertTriangle,CalendarClock,FileCheck2,UploadCloud,FileText,Eye,Trash2}from"lucide-react";import{toast}from"sonner";
interface FormState{placa:string;modelo:string;marca:string;renavam:string;chassi:string;anoFabricacao:string;anoModelo:string;cor:string;combustivel:string;proprietario:string;situacaoOperacional:"DISPONIVEL"|"EM_VIAGEM"|"MANUTENCAO"|"INATIVO";subcategoria:SubcategoriaVeiculo|"";motoristaId:string;crlvValidade:string;ipvaVencimento:string;ipvaPago:boolean;ipvaValor:string;licenciamentoVencimento:string;licenciamentoValor:string;seguroValidade:string;seguroValor:string;rntrc:string;observacoes:string}
type CrlvParsed={placa?:string;renavam?:string;chassi?:string;marca?:string;modelo?:string;anoFabricacao?:number|null;anoModelo?:number|null;cor?:string;combustivel?:string;proprietario?:string;subcategoria?:SubcategoriaVeiculo|null;exercicio?:number|null;avisos?:string[]};
const emptyForm:FormState={placa:"",modelo:"",marca:"",renavam:"",chassi:"",anoFabricacao:"",anoModelo:"",cor:"",combustivel:"",proprietario:"",situacaoOperacional:"DISPONIVEL",subcategoria:"",motoristaId:"",crlvValidade:"",ipvaVencimento:"",ipvaPago:false,ipvaValor:"",licenciamentoVencimento:"",licenciamentoValor:"",seguroValidade:"",seguroValor:"",rntrc:"",observacoes:""};
const labels:Record<SubcategoriaVeiculo,string>={CAMINHAO:"Caminhão",CARRO:"Carro",MOTO:"Moto"};
const days=(date?:string|null)=>{if(!date)return null;const a=new Date(`${date}T00:00:00`),b=new Date();b.setHours(0,0,0,0);return Math.ceil((a.getTime()-b.getTime())/86400000)};
const status=(date?:string|null)=>{const d=days(date);return d===null?"SEM_DATA":d<0?"VENCIDO":d<=30?"ATENCAO":"OK"};
const dateLabel=(v?:string|null)=>v?v.split("-").reverse().join("/"):"—";
function normalizePlate(v:unknown){return String(v??"").toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-Z0-9]/g,"").slice(0,7)}
function formatPlate(v:unknown){const n=normalizePlate(v);return n.length<=3?n:`${n.slice(0,3)}-${n.slice(3)}`}
export default function VeiculoTab(){const{items,create,update,remove,refresh}=useVeiculos();const{items:motoristas}=useMotoristas();const[open,setOpen]=useState(false);const[editingId,setEditingId]=useState<string|null>(null);const[form,setForm]=useState<FormState>(emptyForm);const[query,setQuery]=useState("");const[saving,setSaving]=useState(false);const[crlvFile,setCrlvFile]=useState<File|null>(null);const[readingCrlv,setReadingCrlv]=useState(false);
 const motoristaById=useMemo(()=>new Map(motoristas.map(x=>[x.id,x])),[motoristas]);const motoristasDisponiveis=useMemo(()=>motoristas.filter(x=>x.status==="ATIVO"||x.id===form.motoristaId),[motoristas,form.motoristaId]);
 const alertas=useMemo(()=>items.flatMap(v=>[
  {v,tipo:"CRLV",data:v.crlvValidade,status:status(v.crlvValidade)},
  {v,tipo:"IPVA",data:v.ipvaVencimento,status:v.ipvaPago?"OK":status(v.ipvaVencimento)},
  {v,tipo:"Licenciamento",data:v.licenciamentoVencimento,status:status(v.licenciamentoVencimento)},
  {v,tipo:"Seguro",data:v.seguroValidade,status:status(v.seguroValidade)}
 ]).filter(a=>a.status==="VENCIDO"||a.status==="ATENCAO").sort((a,b)=>(days(a.data)??99999)-(days(b.data)??99999)),[items]);
 const filtered=useMemo(()=>{const q=norm(query);if(!q)return items;return items.filter(x=>{const mot=x.motoristaId?motoristaById.get(x.motoristaId):null;return norm([x.placa,x.modelo,x.marca,x.renavam,x.chassi,x.proprietario,x.rntrc,mot?.nome].join(" ")).includes(q)})},[items,query,motoristaById]);
 const edit=(x:Veiculo)=>{setCrlvFile(null);setForm({placa:formatPlate(x.placa),modelo:x.modelo||"",marca:x.marca||"",renavam:x.renavam||"",chassi:x.chassi||"",anoFabricacao:x.anoFabricacao?String(x.anoFabricacao):"",anoModelo:x.anoModelo?String(x.anoModelo):"",cor:x.cor||"",combustivel:x.combustivel||"",proprietario:x.proprietario||"",situacaoOperacional:x.situacaoOperacional||"DISPONIVEL",subcategoria:x.subcategoria||"",motoristaId:x.motoristaId||"",crlvValidade:x.crlvValidade||"",ipvaVencimento:x.ipvaVencimento||"",ipvaPago:!!x.ipvaPago,ipvaValor:String(x.ipvaValor||""),licenciamentoVencimento:x.licenciamentoVencimento||"",licenciamentoValor:String(x.licenciamentoValor||""),seguroValidade:x.seguroValidade||"",seguroValor:String(x.seguroValor||""),rntrc:x.rntrc||"",observacoes:x.observacoes||""});setEditingId(x.id);setOpen(true)};
 const handleCrlvFile=async(file:File|null)=>{setCrlvFile(file);if(!file)return;const fd=new FormData();fd.append("arquivo",file);setReadingCrlv(true);try{const{data}=await api.post<CrlvParsed>("/veiculos/crlv-pdf/interpretar",fd,{headers:{"Content-Type":"multipart/form-data"}});setForm(current=>({...current,placa:data.placa?formatPlate(data.placa):current.placa,renavam:data.renavam||current.renavam,chassi:data.chassi||current.chassi,marca:data.marca||current.marca,modelo:data.modelo||current.modelo,anoFabricacao:data.anoFabricacao?String(data.anoFabricacao):current.anoFabricacao,anoModelo:data.anoModelo?String(data.anoModelo):current.anoModelo,cor:data.cor||current.cor,combustivel:data.combustivel||current.combustivel,proprietario:data.proprietario||current.proprietario,subcategoria:data.subcategoria||current.subcategoria}));const principais=[data.placa,data.renavam,data.chassi,data.marca||data.modelo].filter(Boolean).length;toast.success(`CRLV lido: ${principais} dado(s) principal(is) preenchido(s).${data.exercicio?` Exercício ${data.exercicio}.`:""}`);if(data.avisos?.length)toast.info(data.avisos.join(" "));}catch(e:any){toast.error(e.response?.data?.message||"Não foi possível interpretar este CRLV automaticamente. O PDF continuará anexado e os campos podem ser preenchidos manualmente.")}finally{setReadingCrlv(false)}};
 const uploadCrlv=async(id:string)=>{if(!crlvFile)return;const fd=new FormData();fd.append("arquivo",crlvFile);await api.post(`/veiculos/${id}/crlv-pdf`,fd,{headers:{"Content-Type":"multipart/form-data"}})};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(saving)return;const placa=formatPlate(form.placa);if(normalizePlate(placa).length!==7)return toast.error("Informe uma placa válida.");if(!form.subcategoria)return toast.error("Selecione a subcategoria.");if(!form.motoristaId)return toast.error("Selecione o motorista.");const payload={...form,placa,anoFabricacao:form.anoFabricacao?Number(form.anoFabricacao):null,anoModelo:form.anoModelo?Number(form.anoModelo):null,subcategoria:form.subcategoria,motoristaId:form.motoristaId,ipvaPago:form.ipvaPago,ipvaValor:Number(form.ipvaValor)||0,licenciamentoValor:Number(form.licenciamentoValor)||0,seguroValor:Number(form.seguroValor)||0};setSaving(true);try{const saved=editingId?await update(editingId,payload):await create(payload);await uploadCrlv(saved.id);if(crlvFile)await refresh();setOpen(false);toast.success("Veículo salvo com sucesso!")}catch(e:any){toast.error(e.response?.data?.message||"Erro ao salvar veículo.")}finally{setSaving(false)}};
 const columns:any[]=[
  {key:"placa",label:"Veículo",render:(x:Veiculo)=><div><div className="flex items-center gap-2 font-mono font-bold"><Truck className="h-4 w-4"/>{formatPlate(x.placa)}</div><div className="text-xs text-muted-foreground">{[x.marca,x.modelo].filter(Boolean).join(" ")||"Modelo não informado"}</div></div>},
  {key:"renavam",label:"RENAVAM",render:(x:Veiculo)=><span>{x.renavam||"—"}</span>},
  {key:"crlv",label:"CRLV",render:(x:Veiculo)=><Validity date={x.crlvValidade}/>},
  {key:"ipva",label:"IPVA",render:(x:Veiculo)=><div><span className={x.ipvaPago?"text-green-600":"text-muted-foreground"}>{x.ipvaPago?"Pago":"Pendente"}</span><div className="text-xs">{dateLabel(x.ipvaVencimento)}</div></div>},
  {key:"situacaoOperacional",label:"Situação",render:(x:Veiculo)=><span className="text-xs font-semibold">{x.situacaoOperacional||"DISPONIVEL"}</span>},{key:"motorista",label:"Motorista",render:(x:Veiculo)=><span>{x.motoristaId?motoristaById.get(x.motoristaId)?.nome||"—":"—"}</span>}
 ];
 return <div className="space-y-4">
  <div className="grid gap-3 sm:grid-cols-3"><Card><CardContent className="p-4"><div className="text-xs text-muted-foreground">Veículos cadastrados</div><div className="mt-1 text-2xl font-bold">{items.length}</div></CardContent></Card><Card><CardContent className="p-4"><div className="flex justify-between text-xs text-muted-foreground"><span>Documentos vencidos</span><AlertTriangle className="h-4 w-4"/></div><div className="mt-1 text-2xl font-bold">{alertas.filter(a=>a.status==="VENCIDO").length}</div></CardContent></Card><Card><CardContent className="p-4"><div className="flex justify-between text-xs text-muted-foreground"><span>Vencem em 30 dias</span><CalendarClock className="h-4 w-4"/></div><div className="mt-1 text-2xl font-bold">{alertas.filter(a=>a.status==="ATENCAO").length}</div></CardContent></Card></div>
  {alertas.length>0&&<div className="rounded-xl border p-4"><div className="mb-3 flex items-center gap-2 font-semibold"><AlertTriangle className="h-4 w-4"/>Alertas da frota</div><div className="grid gap-2 md:grid-cols-2">{alertas.slice(0,8).map((a,i)=><div key={`${a.v.id}-${a.tipo}-${i}`} className="rounded-lg border p-3 text-sm"><div className="font-medium">{formatPlate(a.v.placa)} · {a.tipo}</div><div className={a.status==="VENCIDO"?"text-red-600":"text-amber-600"}>{a.status==="VENCIDO"?"Vencido":"Próximo do vencimento"} · {dateLabel(a.data)}</div></div>)}</div></div>}
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="w-full sm:max-w-xl"><p className="mb-2 text-sm text-muted-foreground">{items.length} veículo(s) cadastrado(s)</p><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Placa, RENAVAM, chassi, modelo, motorista..."/></div><Button onClick={()=>{setForm(emptyForm);setEditingId(null);setCrlvFile(null);setOpen(true)}}><Plus className="mr-1 h-4 w-4"/>Novo Veículo</Button></div>
  <DataTable columns={columns} data={filtered} onEdit={edit} onDelete={x=>remove(x.id)} emptyMessage="Nenhum veículo encontrado."/>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-h-[90vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>{editingId?"Editar Veículo":"Novo Veículo"}</DialogTitle></DialogHeader><form onSubmit={save} className="space-y-5">
   <Section title="Identificação"><div className="grid gap-3 md:grid-cols-4"><Field label="Placa"><Input value={form.placa} onChange={e=>setForm({...form,placa:formatPlate(e.target.value)})}/></Field><Field label="RENAVAM"><Input value={form.renavam} onChange={e=>setForm({...form,renavam:e.target.value})}/></Field><Field label="Chassi"><Input value={form.chassi} onChange={e=>setForm({...form,chassi:e.target.value.toUpperCase()})}/></Field><Field label="RNTRC / ANTT"><Input value={form.rntrc} onChange={e=>setForm({...form,rntrc:e.target.value})}/></Field><Field label="Marca"><Input value={form.marca} onChange={e=>setForm({...form,marca:e.target.value})}/></Field><Field label="Modelo"><Input value={form.modelo} onChange={e=>setForm({...form,modelo:e.target.value})}/></Field><Field label="Ano fabricação"><Input type="number" value={form.anoFabricacao} onChange={e=>setForm({...form,anoFabricacao:e.target.value})}/></Field><Field label="Ano modelo"><Input type="number" value={form.anoModelo} onChange={e=>setForm({...form,anoModelo:e.target.value})}/></Field><Field label="Cor"><Input value={form.cor} onChange={e=>setForm({...form,cor:e.target.value})}/></Field><Field label="Combustível"><Input value={form.combustivel} onChange={e=>setForm({...form,combustivel:e.target.value})}/></Field><Field label="Proprietário"><Input value={form.proprietario} onChange={e=>setForm({...form,proprietario:e.target.value})}/></Field></div></Section>
   <Section title="Operação"><div className="grid gap-3 md:grid-cols-2"><Field label="Subcategoria"><Select value={form.subcategoria} onValueChange={v=>setForm({...form,subcategoria:v as SubcategoriaVeiculo})}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent><SelectItem value="CAMINHAO">Caminhão</SelectItem><SelectItem value="CARRO">Carro</SelectItem><SelectItem value="MOTO">Moto</SelectItem></SelectContent></Select></Field><Field label="Situação operacional"><Select value={form.situacaoOperacional} onValueChange={v=>setForm({...form,situacaoOperacional:v as FormState["situacaoOperacional"]})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="DISPONIVEL">Disponível</SelectItem><SelectItem value="EM_VIAGEM">Em viagem</SelectItem><SelectItem value="MANUTENCAO">Manutenção</SelectItem><SelectItem value="INATIVO">Inativo</SelectItem></SelectContent></Select></Field><Field label="Motorista vinculado"><Select value={form.motoristaId} onValueChange={v=>setForm({...form,motoristaId:v})}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{motoristasDisponiveis.map(m=><SelectItem key={m.id} value={m.id}>{m.nome}</SelectItem>)}</SelectContent></Select></Field></div></Section>
   <Section title="Documentos, impostos e seguros"><div className="grid gap-3 md:grid-cols-3"><Field label="Validade CRLV"><Input type="date" value={form.crlvValidade} onChange={e=>setForm({...form,crlvValidade:e.target.value})}/></Field><Field label="Vencimento IPVA"><Input type="date" value={form.ipvaVencimento} onChange={e=>setForm({...form,ipvaVencimento:e.target.value})}/></Field><Field label="Valor IPVA"><Input type="number" step="0.01" value={form.ipvaValor} onChange={e=>setForm({...form,ipvaValor:e.target.value})}/></Field><Field label="IPVA pago"><label className="mt-2 flex h-10 items-center gap-2 rounded-md border px-3"><input type="checkbox" checked={form.ipvaPago} onChange={e=>setForm({...form,ipvaPago:e.target.checked})}/>Sim, quitado</label></Field><Field label="Licenciamento"><Input type="date" value={form.licenciamentoVencimento} onChange={e=>setForm({...form,licenciamentoVencimento:e.target.value})}/></Field><Field label="Valor licenciamento"><Input type="number" step="0.01" value={form.licenciamentoValor} onChange={e=>setForm({...form,licenciamentoValor:e.target.value})}/></Field><Field label="Validade seguro"><Input type="date" value={form.seguroValidade} onChange={e=>setForm({...form,seguroValidade:e.target.value})}/></Field><Field label="Valor seguro"><Input type="number" step="0.01" value={form.seguroValor} onChange={e=>setForm({...form,seguroValor:e.target.value})}/></Field></div></Section>
   <Section title="Documento do veículo"><CrlvDrop file={crlvFile} onFile={handleCrlvFile} loading={readingCrlv} storedName={editingId?items.find(x=>x.id===editingId)?.crlvPdfNome:undefined} stored={!!(editingId&&items.find(x=>x.id===editingId)?.crlvPdfStored)} onView={editingId?()=>window.open(`/api/veiculos/${editingId}/crlv-pdf`,"_blank"):undefined} onRemove={editingId?async()=>{await api.delete(`/veiculos/${editingId}/crlv-pdf`);await refresh();toast.success("PDF do CRLV removido.")}:undefined}/></Section>
   <Section title="Observações"><Field label="Observações do veículo"><Input value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></Field></Section>
   <DialogFooter><Button type="submit" disabled={saving||readingCrlv}>{saving?"Salvando...":"Salvar"}</Button></DialogFooter>
  </form></DialogContent></Dialog>
 </div>}
function Validity({date}:{date?:string|null}){const s=status(date);return <span className={s==="VENCIDO"?"text-red-600":s==="ATENCAO"?"text-amber-600":"text-muted-foreground"}>{dateLabel(date)}</span>}
function Section({title,children}:{title:string;children:ReactNode}){return <div><div className="mb-2 flex items-center gap-2 text-sm font-semibold"><FileCheck2 className="h-4 w-4"/>{title}</div>{children}</div>}
function Field({label,children}:{label:string;children:ReactNode}){return <div className="space-y-1"><Label>{label}</Label>{children}</div>}
function norm(v:unknown){return String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}

function CrlvDrop({file,onFile,loading,storedName,stored,onView,onRemove}:{file:File|null;onFile:(f:File|null)=>void|Promise<void>;loading?:boolean;storedName?:string;stored?:boolean;onView?:()=>void;onRemove?:()=>void|Promise<void>}){const input=useRef<HTMLInputElement|null>(null);const accept=(f?:File)=>{if(!f)return;if(f.type!=="application/pdf"&&!f.name.toLowerCase().endsWith(".pdf")){toast.error("Envie somente o CRLV em PDF.");return}if(f.size>10*1024*1024){toast.error("O PDF deve ter no máximo 10 MB.");return}onFile(f)};return <div className="space-y-2"><div onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add("border-primary")}} onDragLeave={e=>e.currentTarget.classList.remove("border-primary")} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove("border-primary");accept(e.dataTransfer.files?.[0])}} onClick={()=>input.current?.click()} className="cursor-pointer rounded-xl border-2 border-dashed p-6 text-center transition-colors hover:border-primary"><input ref={input} className="hidden" type="file" accept="application/pdf,.pdf" onChange={e=>accept(e.target.files?.[0])}/><UploadCloud className="mx-auto mb-2 h-6 w-6"/><div className="font-medium">{loading?"Lendo dados do CRLV...":file?file.name:"Arraste e solte o CRLV aqui"}</div><div className="mt-1 text-sm text-muted-foreground">{loading?"Aguarde enquanto placa, RENAVAM, chassi e demais dados são identificados.":"ou clique para escolher o PDF · preenchimento automático · até 10 MB"}</div></div>{file&&<Button type="button" size="sm" variant="ghost" disabled={loading} onClick={()=>onFile(null)}><Trash2 className="mr-1 h-4 w-4"/>Remover seleção</Button>}{stored&&!file&&<div className="flex flex-wrap items-center gap-2 rounded-md border p-3 text-sm"><FileText className="h-4 w-4"/><span className="min-w-0 flex-1 truncate">{storedName||"CRLV cadastrado"}</span>{onView&&<Button type="button" size="sm" variant="outline" onClick={e=>{e.stopPropagation();onView()}}><Eye className="mr-1 h-4 w-4"/>Visualizar</Button>}{onRemove&&<Button type="button" size="sm" variant="ghost" onClick={async e=>{e.stopPropagation();if(confirm("Remover o PDF do CRLV?"))await onRemove()}}><Trash2 className="h-4 w-4"/></Button>}</div>}</div>}
