import { prisma } from "../lib/prisma.js";
import { AppError } from "../utils/app-error.js";
import { parseDateOnly } from "../utils/date.js";
import { dateOnly, number, created } from "../utils/serialize.js";
const d=(v:any)=>v?parseDateOnly(v):null;
const plano=(x:any)=>({...x,intervaloKm:x.intervaloKm==null?null:number(x.intervaloKm),ultimoKm:x.ultimoKm==null?null:number(x.ultimoKm),proximoKm:x.proximoKm==null?null:number(x.proximoKm),ultimaData:x.ultimaData?dateOnly(x.ultimaData):null,proximaData:x.proximaData?dateOnly(x.proximaData):null,createdAt:created(x.createdAt)});
const os=(x:any)=>({...x,kmAbertura:x.kmAbertura==null?null:number(x.kmAbertura),valorPecas:number(x.valorPecas),valorMaoObra:number(x.valorMaoObra),valorOutros:number(x.valorOutros),valorTotal:number(x.valorPecas)+number(x.valorMaoObra)+number(x.valorOutros),dataAbertura:dateOnly(x.dataAbertura),dataConclusao:x.dataConclusao?dateOnly(x.dataConclusao):null,createdAt:created(x.createdAt)});
export const manutencaoService={
 async dashboard(){const [planos,ordens,docs,ab]=await Promise.all([prisma.planoManutencao.findMany({where:{ativo:true}}),prisma.ordemServico.findMany(),prisma.documentoFrota.findMany(),prisma.abastecimento.findMany({orderBy:{dataEmissao:"desc"}})]);const km=new Map<string,number>();for(const a of ab){if(!km.has(a.veiculoId))km.set(a.veiculoId,number(a.hodometro));}const hoje=new Date(),limite=new Date();limite.setDate(limite.getDate()+30);const alertas:any[]=[];for(const p of planos){const atual=km.get(p.veiculoId)||0;if(p.proximoKm!=null&&number(p.proximoKm)-atual<=2000)alertas.push({tipo:"KM",veiculoId:p.veiculoId,titulo:p.nome,detalhe:`${Math.max(0,number(p.proximoKm)-atual).toFixed(0)} km restantes`});if(p.proximaData&&p.proximaData<=limite)alertas.push({tipo:"DATA",veiculoId:p.veiculoId,titulo:p.nome,detalhe:`Vence em ${dateOnly(p.proximaData)}`});}for(const x of docs){if(x.validade&&x.validade<=limite)alertas.push({tipo:"DOCUMENTO",veiculoId:x.veiculoId,titulo:x.tipo,detalhe:`Validade ${dateOnly(x.validade)}`});}return{osAbertas:ordens.filter(x=>x.status!=="CONCLUIDA"&&x.status!=="CANCELADA").length,planosAtivos:planos.length,alertas,documentos:docs.length,custoTotal:ordens.filter(x=>x.status==="CONCLUIDA").reduce((a,x)=>a+number(x.valorPecas)+number(x.valorMaoObra)+number(x.valorOutros),0)}},
 async planos(){return (await prisma.planoManutencao.findMany({orderBy:{createdAt:"desc"}})).map(plano)},
 async criarPlano(i:any){const ultimoKm=i.ultimoKm===""?null:i.ultimoKm,intervaloKm=i.intervaloKm===""?null:i.intervaloKm;return plano(await prisma.planoManutencao.create({data:{veiculoId:i.veiculoId,nome:i.nome,categoria:i.categoria||"PREVENTIVA",intervaloKm,intervaloDias:i.intervaloDias||null,ultimoKm,ultimaData:d(i.ultimaData),proximoKm:i.proximoKm||((ultimoKm!=null&&intervaloKm!=null)?number(ultimoKm)+number(intervaloKm):null),proximaData:d(i.proximaData),observacoes:i.observacoes||""}}))},
 async removerPlano(id:string){await prisma.planoManutencao.delete({where:{id}})},
 async ordens(){return (await prisma.ordemServico.findMany({orderBy:[{dataAbertura:"desc"},{createdAt:"desc"}]})).map(os)},
 async criarOs(i:any){const count=await prisma.ordemServico.count();return os(await prisma.ordemServico.create({data:{numero:`OS-${String(count+1).padStart(5,"0")}`,veiculoId:i.veiculoId,tipo:i.tipo||"PREVENTIVA",status:"ABERTA",descricao:i.descricao,fornecedor:i.fornecedor||"",kmAbertura:i.kmAbertura||null,dataAbertura:parseDateOnly(i.dataAbertura),valorPecas:i.valorPecas||0,valorMaoObra:i.valorMaoObra||0,valorOutros:i.valorOutros||0,observacoes:i.observacoes||""}}))},
 async concluirOs(id:string,i:any){const x=await prisma.ordemServico.findUnique({where:{id}});if(!x)throw new AppError(404,"OS não encontrada.");const upd=await prisma.ordemServico.update({where:{id},data:{status:"CONCLUIDA",dataConclusao:parseDateOnly(i.dataConclusao),valorPecas:i.valorPecas??x.valorPecas,valorMaoObra:i.valorMaoObra??x.valorMaoObra,valorOutros:i.valorOutros??x.valorOutros}});const total=number(upd.valorPecas)+number(upd.valorMaoObra)+number(upd.valorOutros);if(total>0)await prisma.lancamentoFinanceiro.create({data:{tipo:"DESPESA",descricao:`Manutenção ${upd.numero} - ${upd.descricao.slice(0,120)}`,categoria:"Manutenção",valor:total,dataCompetencia:parseDateOnly(i.dataConclusao),status:"PENDENTE",veiculoId:upd.veiculoId,fornecedor:upd.fornecedor}});return os(upd)},
 async documentos(){return (await prisma.documentoFrota.findMany({orderBy:{validade:"asc"}})).map((x:any)=>({...x,validade:x.validade?dateOnly(x.validade):null,createdAt:created(x.createdAt)}))},
 async criarDocumento(i:any){const x=await prisma.documentoFrota.create({data:{veiculoId:i.veiculoId,tipo:i.tipo,numero:i.numero||"",validade:d(i.validade),observacoes:i.observacoes||""}});return{...x,validade:x.validade?dateOnly(x.validade):null,createdAt:created(x.createdAt)}},
 async removerDocumento(id:string){await prisma.documentoFrota.delete({where:{id}})}
};